import json
import re

def process_file(filepath, replacements):
    with open(filepath, 'r', encoding='utf-8') as f:
        text = f.read()
    
    for k, v in replacements.items():
        text = text.replace(k, v)
        
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(text)

r100 = {
    '<title>Compress Image to 100KB - Free Online File Size Reducer | PicEte</title>': '<title>이미지를 100KB로 압축 - 무료 온라인 파일 크기 축소기 | PicEte</title>',
    '<meta content="Compress images to exactly 100KB. Free online tool to reduce image file size to 100KB while maintaining quality. Perfect for form uploads and document submissions." name="description"/>': '<meta content="이미지를 정확히 100KB로 압축합니다. 품질을 유지하면서 이미지 파일 크기를 100KB로 줄이는 무료 온라인 도구입니다. 양식 업로드 및 문서 제출에 완벽합니다." name="description"/>',
    '<meta content="compress image to 100kb, reduce file size, image optimizer, 100KB limit" name="keywords"/>': '<meta content="100kb로 이미지 압축, 파일 크기 축소, 이미지 최적화, 100KB 제한" name="keywords"/>',
    '<meta content="Compress Image to 100KB - File Size Optimizer" property="og:title"/>': '<meta content="이미지를 100KB로 압축 - 파일 크기 최적화" property="og:title"/>',
    '<meta content="Free online tool to compress images to 100KB for uploads and forms." property="og:description"/>': '<meta content="업로드 및 양식 제출을 위해 이미지를 100KB로 압축하는 무료 온라인 도구입니다." property="og:description"/>',
    '"name": "Compress Image to 100KB"': '"name": "이미지를 100KB로 압축"',
    '"description": "Free online tool to compress images to exactly 100KB file size"': '"description": "이미지 파일 크기를 정확히 100KB로 압축하는 무료 온라인 도구"',
    '"name": "How do I get an image under 100KB?"': '"name": "이미지를 100KB 미만으로 만들려면 어떻게 해야 하나요?"',
    '"text": "Start with a reasonable resolution (under 2000px wide). Use the quality slider between 50-70% for most images. Photos with lots of detail may need lower quality settings, while simple graphics with solid colors can stay crisp even at higher compression."': '"text": "합리적인 해상도(폭 2000px 미만)로 시작하세요. 대부분의 이미지에 대해 품질 슬라이더를 50-70% 사이로 사용하세요. 디테일이 많은 사진은 더 낮은 품질 설정이 필요할 수 있는 반면, 단색의 단순한 그래픽은 압축률이 높아도 선명함을 유지할 수 있습니다."',
    '"name": "What\'s the best quality setting to stay under 100KB?"': '"name": "100KB 미만을 유지하기 위한 최적의 품질 설정은 무엇인가요?"',
    '"text": "For a 1920\\u00d71080 photo, 40-60% quality usually lands under 100KB. For smaller images like 800\\u00d7800, 60-80% works. The tool shows the output file size in real time, so experiment with the slider to find the best quality that keeps you under the limit."': '"text": "1920\\u00d71080 사진의 경우 보통 40-60% 품질이 100KB 미만이 됩니다. 800\\u00d7800과 같은 더 작은 이미지의 경우 60-80%가 적당합니다. 이 도구는 결과 파일 크기를 실시간으로 보여주므로 슬라이더를 조절하여 제한 내에서 유지할 수 있는 최적의 품질을 찾아보세요."',
    '"name": "Why does my image need to be under 100KB?"': '"name": "내 이미지가 왜 100KB 미만이어야 하나요?"',
    '"text": "100KB is a common limit for email attachments, forum uploads, job application portals, and some CMS platforms. Smaller images also improve page load speed \\u2014 every 100KB saved makes your page load noticeably faster, especially on mobile networks."': '"text": "100KB는 이메일 첨부 파일, 포럼 업로드, 구직 포털 및 일부 CMS 플랫폼에서 흔히 사용되는 제한입니다. 또한 이미지가 작을수록 페이지 로드 속도가 향상됩니다. 100KB를 절약할 때마다 특히 모바일 네트워크에서 페이지 로드 속도가 눈에 띄게 빨라집니다."',
    '"name": "Can I batch compress images to under 100KB?"': '"name": "여러 이미지를 한 번에 100KB 미만으로 일괄 압축할 수 있나요?"',
    '"text": "Yes, upload multiple images and the tool processes them all simultaneously. Since each image needs different compression levels to hit 100KB, adjust the quality slider for your batch and preview the results before downloading."': '"text": "네, 여러 이미지를 업로드하면 도구가 동시에 모두 처리합니다. 100KB에 맞추기 위해 각 이미지마다 다른 압축 수준이 필요하므로 일괄 처리를 위해 품질 슬라이더를 조정하고 다운로드하기 전에 결과를 미리 확인하세요."',
    '<p class="tagline">Image Compressor</p>': '<p class="tagline">이미지 압축기</p>',
    '<a class="nav-link" href="../">Home</a>': '<a class="nav-link" href="../">홈</a>',
    '<a class="nav-link" href="../#tools">More Tools</a>': '<a class="nav-link" href="../#tools">더 많은 도구</a>',
    '<div class="breadcrumb"><a href="https://picete.com/">Home</a><span class="separator">›</span><a href="../compress-image/">Image Compressor</a><span class="separator">›</span><span class="current">100KB</span></div>': '<div class="breadcrumb"><a href="https://picete.com/">홈</a><span class="separator">›</span><a href="../compress-image/">이미지 압축기</a><span class="separator">›</span><span class="current">100KB</span></div>',
    '<h1 class="hero-title">Compress Image to 100KB</h1>': '<h1 class="hero-title">이미지를 100KB로 압축</h1>',
    '<h2 class="hero-subtitle">Meet File Size Limits Without Losing Quality</h2>': '<h2 class="hero-subtitle">품질 저하 없이 파일 크기 제한 맞추기</h2>',
    'Need to compress an image to exactly 100KB? Many online forms, job applications, and document submissions have strict file size limits. PicEte intelligently reduces your image to meet the 100KB requirement while preserving as much visual quality as possible. Upload any image — our tool adjusts compression automatically to hit the target size.': '이미지를 정확히 100KB로 압축해야 하나요? 많은 온라인 양식, 구직 신청서, 문서 제출에는 엄격한 파일 크기 제한이 있습니다. PicEte는 시각적 품질을 최대한 유지하면서 100KB 요구 사항을 충족하도록 이미지를 지능적으로 줄여줍니다. 어떤 이미지든 업로드하세요. 저희 도구가 목표 크기에 도달하도록 압축을 자동으로 조정합니다.',
    '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">Why Compress to 100KB?</h3>': '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">왜 100KB로 압축하나요?</h3>',
    'The 100KB file size limit is common for government forms, university applications, and online document systems. These restrictions exist to reduce server load and processing time, but they can be frustrating when your photo or scan exceeds the limit. PicEte solves this by applying smart compression that reduces file size without making your image look pixelated or blurry. We optimize JPEG quality settings and strip unnecessary metadata to get you just under the threshold.': '100KB 파일 크기 제한은 정부 양식, 대학 지원서 및 온라인 문서 시스템에서 흔히 사용됩니다. 이러한 제한은 서버 부하 및 처리 시간을 줄이기 위해 존재하지만 사진이나 스캔본이 제한을 초과할 때 짜증날 수 있습니다. PicEte는 이미지가 깨지거나 흐릿하게 보이지 않으면서 파일 크기를 줄이는 스마트 압축을 적용하여 이 문제를 해결합니다. JPEG 품질 설정을 최적화하고 불필요한 메타데이터를 제거하여 기준치 바로 아래로 맞춰줍니다.',
    '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">How PicEte Targets 100KB</h3>': '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">PicEte가 100KB를 맞추는 방법</h3>',
    'Our compressor analyzes your image and progressively increases JPEG compression until the file size reaches approximately 100KB. If your original is significantly larger, we\'ll also resize dimensions strategically to meet the target while keeping the image usable for documents and forms. The process is automatic — no manual tweaking of quality sliders needed. All processing happens locally in your browser, so your photos remain private and never touch a server.': '우리의 압축기는 이미지를 분석하고 파일 크기가 대략 100KB에 도달할 때까지 점진적으로 JPEG 압축을 증가시킵니다. 원본이 상당히 크면 이미지 크기를 전략적으로 조정하여 문서 및 양식에서 이미지를 사용할 수 있게 유지하면서 목표를 달성합니다. 이 과정은 자동화되어 있어 품질 슬라이더를 수동으로 조정할 필요가 없습니다. 모든 처리는 브라우저 내에서 로컬로 진행되므로 사진은 비공개로 유지되며 서버에 전송되지 않습니다.',
    '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">Common Use Cases for 100KB Compression</h3>': '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">100KB 압축의 일반적인 사용 사례</h3>',
    '<li>Visa and passport photo uploads for online applications</li>': '<li>온라인 지원서용 비자 및 여권 사진 업로드</li>',
    '<li>Government document submissions with strict size limits</li>': '<li>엄격한 크기 제한이 있는 정부 문서 제출</li>',
    '<li>University application forms and standardized test uploads</li>': '<li>대학 지원서 양식 및 표준화 시험 업로드</li>',
    '<li>Job application document and photo attachments</li>': '<li>구직 지원 문서 및 사진 첨부</li>',
    '<li>Online form entries with file size restrictions</li>': '<li>파일 크기 제한이 있는 온라인 양식 항목</li>',
    'Use PicEte Image Compressor Free →': '무료 PicEte 이미지 압축기 사용하기 →',
    'Free • No signup • Private browser-based processing': '무료 • 가입 불필요 • 비공개 브라우저 기반 처리',
    '<h3 style="font-size: 1.125rem; margin-bottom: 1rem; color: var(--text-color);">Related Compression Options</h3>': '<h3 style="font-size: 1.125rem; margin-bottom: 1rem; color: var(--text-color);">관련 압축 옵션</h3>',
    '<h4 style="font-size: 1rem; margin-bottom: 0.5rem;">Other File Size Targets</h4>': '<h4 style="font-size: 1rem; margin-bottom: 0.5rem;">다른 파일 크기 목표</h4>',
    '<li><a href="../compress-image-to-50kb/">Compress to 50KB</a> — Smaller limit</li>': '<li><a href="../compress-image-to-50kb/">50KB로 압축</a> — 더 작은 제한</li>',
    '<li><a href="../compress-jpg-to-200kb/">Compress JPG to 200KB</a> — Higher quality</li>': '<li><a href="../compress-jpg-to-200kb/">JPG를 200KB로 압축</a> — 더 높은 품질</li>',
    '<li><a href="../compress-image/">General Compressor</a> — Custom size</li>': '<li><a href="../compress-image/">일반 압축기</a> — 맞춤형 크기</li>',
    '<h2 class="section-title">Frequently Asked Questions</h2>': '<h2 class="section-title">자주 묻는 질문</h2>',
    '<summary class="faq-question">How do I get an image under 100KB?</summary>': '<summary class="faq-question">이미지를 100KB 미만으로 만들려면 어떻게 해야 하나요?</summary>',
    '<p class="faq-answer">Start with a reasonable resolution (under 2000px wide). Use the quality slider between 50-70% for most images. Photos with lots of detail may need lower quality settings, while simple graphics with solid colors can stay crisp even at higher compression.</p>': '<p class="faq-answer">합리적인 해상도(폭 2000px 미만)로 시작하세요. 대부분의 이미지에 대해 품질 슬라이더를 50-70% 사이로 사용하세요. 디테일이 많은 사진은 더 낮은 품질 설정이 필요할 수 있는 반면, 단색의 단순한 그래픽은 압축률이 높아도 선명함을 유지할 수 있습니다.</p>',
    '<summary class="faq-question">What\'s the best quality setting to stay under 100KB?</summary>': '<summary class="faq-question">100KB 미만을 유지하기 위한 최적의 품질 설정은 무엇인가요?</summary>',
    '<p class="faq-answer">For a 1920×1080 photo, 40-60% quality usually lands under 100KB. For smaller images like 800×800, 60-80% works. The tool shows the output file size in real time, so experiment with the slider to find the best quality that keeps you under the limit.</p>': '<p class="faq-answer">1920×1080 사진의 경우 보통 40-60% 품질이 100KB 미만이 됩니다. 800×800과 같은 더 작은 이미지의 경우 60-80%가 적당합니다. 이 도구는 결과 파일 크기를 실시간으로 보여주므로 슬라이더를 조절하여 제한 내에서 유지할 수 있는 최적의 품질을 찾아보세요.</p>',
    '<summary class="faq-question">Why does my image need to be under 100KB?</summary>': '<summary class="faq-question">내 이미지가 왜 100KB 미만이어야 하나요?</summary>',
    '<p class="faq-answer">100KB is a common limit for email attachments, forum uploads, job application portals, and some CMS platforms. Smaller images also improve page load speed — every 100KB saved makes your page load noticeably faster, especially on mobile networks.</p>': '<p class="faq-answer">100KB는 이메일 첨부 파일, 포럼 업로드, 구직 포털 및 일부 CMS 플랫폼에서 흔히 사용되는 제한입니다. 또한 이미지가 작을수록 페이지 로드 속도가 향상됩니다. 100KB를 절약할 때마다 특히 모바일 네트워크에서 페이지 로드 속도가 눈에 띄게 빨라집니다.</p>',
    '<summary class="faq-question">Can I batch compress images to under 100KB?</summary>': '<summary class="faq-question">여러 이미지를 한 번에 100KB 미만으로 일괄 압축할 수 있나요?</summary>',
    '<p class="faq-answer">Yes, upload multiple images and the tool processes them all simultaneously. Since each image needs different compression levels to hit 100KB, adjust the quality slider for your batch and preview the results before downloading.</p>': '<p class="faq-answer">네, 여러 이미지를 업로드하면 도구가 동시에 모두 처리합니다. 100KB에 맞추기 위해 각 이미지마다 다른 압축 수준이 필요하므로 일괄 처리를 위해 품질 슬라이더를 조정하고 다운로드하기 전에 결과를 미리 확인하세요.</p>',
    '<h4>More Tools</h4>': '<h4>더 많은 도구</h4>',
    '<li><a href="../compress-image/">Image Compressor</a></li>': '<li><a href="../compress-image/">이미지 압축기</a></li>',
    '<li><a href="../resize-image/">Image Resizer</a></li>': '<li><a href="../resize-image/">이미지 크기 조절기</a></li>',
    '<li><a href="../png-to-jpg/">PNG to JPG</a></li>': '<li><a href="../png-to-jpg/">PNG를 JPG로</a></li>',
    '<li><a href="../webp-to-png/">WebP to PNG</a></li>': '<li><a href="../webp-to-png/">WebP를 PNG로</a></li>',
    '<h4>About</h4>': '<h4>소개</h4>',
    '<li><a href="../">Back to Home</a></li>': '<li><a href="../">홈으로 돌아가기</a></li>',
    '<li><a href="/privacy-policy.html">Privacy Policy</a></li>': '<li><a href="/privacy-policy.html">개인정보 처리방침</a></li>',
    '<h4>Partner Sites</h4>': '<h4>파트너 사이트</h4>',
    '<li><a href="https://mockupshot.online/">MockupShot - Screenshot Mockup</a></li>': '<li><a href="https://mockupshot.online/">MockupShot - 스크린샷 목업</a></li>',
    '<li><a href="https://ilovepalette.com/">ILovePalette - Color Tools</a></li>': '<li><a href="https://ilovepalette.com/">ILovePalette - 색상 도구</a></li>',
    '<p>© 2024 PicEte. All rights reserved.</p>': '<p>© 2024 PicEte. 모든 권리 보유.</p>'
}

r200 = {
    '<title>Compress Image to 200KB - Free Online File Size Reducer | PicEte</title>': '<title>이미지를 200KB로 압축 - 무료 온라인 파일 크기 축소기 | PicEte</title>',
    '<meta content="Compress images to under 200KB. Free online tool to reduce image file size to 200KB while maintaining good quality." name="description"/>': '<meta content="이미지를 200KB 미만으로 압축합니다. 좋은 품질을 유지하면서 이미지 파일 크기를 200KB로 줄이는 무료 온라인 도구입니다." name="description"/>',
    '<meta content="compress image to 200kb, reduce file size, image optimizer, 200KB limit" name="keywords"/>': '<meta content="200kb로 이미지 압축, 파일 크기 축소, 이미지 최적화, 200KB 제한" name="keywords"/>',
    '<meta content="Compress Image to 200KB - File Size Optimizer" property="og:title"/>': '<meta content="이미지를 200KB로 압축 - 파일 크기 최적화" property="og:title"/>',
    '<meta content="Free online tool to compress images to 200KB for uploads and forms." property="og:description"/>': '<meta content="업로드 및 양식 제출을 위해 이미지를 200KB로 압축하는 무료 온라인 도구입니다." property="og:description"/>',
    '"name": "Compress Image to 200KB"': '"name": "이미지를 200KB로 압축"',
    '"description": "Free online tool to compress images to under 200KB file size"': '"description": "이미지 파일 크기를 200KB 미만으로 압축하는 무료 온라인 도구"',
    '"name": "How do I compress an image to under 200KB?"': '"name": "이미지를 어떻게 200KB 미만으로 압축하나요?"',
    '"text": "Upload your image to PicEte and use the quality slider to find the right balance. For a 1920x1080 photo, 50-70% quality typically lands under 200KB. Smaller images like 800x600 can use 70-85% quality. The tool shows the output file size in real time, so adjust the slider until you hit the 200KB target."': '"text": "PicEte에 이미지를 업로드하고 품질 슬라이더를 사용하여 적절한 균형을 찾으세요. 1920x1080 사진의 경우 보통 50-70% 품질이 200KB 미만이 됩니다. 800x600과 같은 작은 이미지는 70-85% 품질을 사용할 수 있습니다. 도구가 출력 파일 크기를 실시간으로 보여주므로 200KB 목표치에 도달할 때까지 슬라이더를 조정하세요."',
    '"name": "Why do I need to compress images to 200KB?"': '"name": "왜 이미지를 200KB로 압축해야 하나요?"',
    '"text": "200KB is a common file size limit for document uploads, scholarship applications, job portals, and some content management systems. Many online forms reject images larger than 200KB to reduce server load. Compressing your images ensures they\'ll be accepted while maintaining enough quality for most uses."': '"text": "200KB는 문서 업로드, 장학금 신청, 취업 포털 및 일부 콘텐츠 관리 시스템에서 흔히 사용되는 파일 크기 제한입니다. 많은 온라인 양식은 서버 부하를 줄이기 위해 200KB보다 큰 이미지를 거부합니다. 이미지를 압축하면 대부분의 용도에 충분한 품질을 유지하면서 이미지가 허용되도록 보장할 수 있습니다."',
    '"name": "Will compressing to 200KB lose image quality?"': '"name": "200KB로 압축하면 이미지 품질이 저하되나요?"',
    '"text": "Some quality loss is inevitable when compressing to 200KB, but PicEte uses smart JPEG compression that minimizes visible artifacts. At 200KB, most photos look excellent on screens and print well up to 5x7 inches. For critical applications like professional printing, consider whether a higher file size limit is available."': '"text": "200KB로 압축할 때 어느 정도의 품질 저하는 피할 수 없지만, PicEte는 눈에 띄는 아티팩트를 최소화하는 스마트 JPEG 압축을 사용합니다. 200KB에서는 대부분의 사진이 화면에서 훌륭하게 보이며 최대 5x7인치까지 잘 인쇄됩니다. 전문 인쇄와 같은 중요한 작업의 경우 더 높은 파일 크기 제한이 가능한지 고려해 보세요."',
    '"name": "Can I batch compress images to 200KB?"': '"name": "여러 이미지를 한 번에 200KB로 일괄 압축할 수 있나요?"',
    '"text": "Yes. Upload multiple images and the tool processes them all simultaneously. Since each image needs different compression levels to hit 200KB, you may need to adjust the quality slider for each one. Preview the results before downloading to ensure quality meets your needs."': '"text": "네. 여러 이미지를 업로드하면 도구가 동시에 모두 처리합니다. 200KB에 맞추기 위해 각 이미지마다 다른 압축 수준이 필요하므로 각 이미지에 대해 품질 슬라이더를 조정해야 할 수 있습니다. 다운로드하기 전에 결과를 미리 확인하여 품질이 요구 사항을 충족하는지 확인하세요."',
    '<p class="tagline">Image Compressor</p>': '<p class="tagline">이미지 압축기</p>',
    '<a class="nav-link" href="../">Home</a>': '<a class="nav-link" href="../">홈</a>',
    '<a class="nav-link" href="../#tools">More Tools</a>': '<a class="nav-link" href="../#tools">더 많은 도구</a>',
    '<div class="breadcrumb"><a href="https://picete.com/">Home</a><span class="separator">›</span><a href="../compress-image/">Image Compressor</a><span class="separator">›</span><span class="current">200KB</span></div>': '<div class="breadcrumb"><a href="https://picete.com/">홈</a><span class="separator">›</span><a href="../compress-image/">이미지 압축기</a><span class="separator">›</span><span class="current">200KB</span></div>',
    '<h1 class="hero-title">Compress Image to 200KB</h1>': '<h1 class="hero-title">이미지를 200KB로 압축</h1>',
    '<h2 class="hero-subtitle">File Size Limit Made Easy</h2>': '<h2 class="hero-subtitle">파일 크기 제한을 쉽게 해결하세요</h2>',
    'Need to compress an image to exactly 200KB? Many online forms, job applications, and document systems have strict file size limits. PicEte intelligently reduces your image to meet the 200KB requirement while preserving as much visual quality as possible. Upload any image — our tool adjusts compression automatically to hit the target size.': '이미지를 정확히 200KB로 압축해야 하나요? 많은 온라인 양식, 구직 신청서, 문서 시스템에는 엄격한 파일 크기 제한이 있습니다. PicEte는 시각적 품질을 최대한 유지하면서 200KB 요구 사항을 충족하도록 이미지를 지능적으로 줄여줍니다. 어떤 이미지든 업로드하세요. 저희 도구가 목표 크기에 도달하도록 압축을 자동으로 조정합니다.',
    '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">Why Compress to 200KB?</h3>': '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">왜 200KB로 압축하나요?</h3>',
    '200KB is a common file size limit for scholarship applications, government forms, university submissions, and corporate HR portals. These restrictions reduce server load and speed up processing, but they\'re frustrating when your photo or scan exceeds the limit. PicEte solves this by applying smart JPEG compression that reduces file size without making your image look pixelated or blurry. We optimize quality settings and strip unnecessary metadata to get you just under 200KB.': '200KB는 장학금 신청, 정부 양식, 대학 제출 및 기업 인사 포털에서 흔히 사용되는 파일 크기 제한입니다. 이러한 제한은 서버 부하를 줄이고 처리를 빠르게 하지만 사진이나 스캔본이 제한을 초과할 때 짜증날 수 있습니다. PicEte는 이미지가 깨지거나 흐릿하게 보이지 않으면서 파일 크기를 줄이는 스마트 JPEG 압축을 적용하여 이 문제를 해결합니다. 품질 설정을 최적화하고 불필요한 메타데이터를 제거하여 200KB 바로 아래로 맞춰줍니다.',
    '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">How PicEte Targets 200KB</h3>': '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">PicEte가 200KB를 맞추는 방법</h3>',
    'Our compressor analyzes your image and progressively increases JPEG compression until the file size reaches approximately 200KB. If your original is significantly larger, we\'ll also resize dimensions strategically to meet the target while keeping the image usable. The process is automatic — no manual tweaking of quality sliders needed. All processing happens locally in your browser, so your photos remain private and never touch a server.': '우리의 압축기는 이미지를 분석하고 파일 크기가 대략 200KB에 도달할 때까지 점진적으로 JPEG 압축을 증가시킵니다. 원본이 상당히 크면 문서 및 양식에서 이미지를 사용할 수 있게 유지하면서 목표를 달성하기 위해 이미지 크기를 전략적으로 조정합니다. 이 과정은 자동화되어 있어 품질 슬라이더를 수동으로 조정할 필요가 없습니다. 모든 처리는 브라우저 내에서 로컬로 진행되므로 사진은 비공개로 유지되며 서버에 전송되지 않습니다.',
    '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">Common Use Cases for 200KB Compression</h3>': '<h3 style="font-size: 1.25rem; margin-bottom: 1rem; color: var(--text-color);">200KB 압축의 일반적인 사용 사례</h3>',
    '<li>Scholarship application photo uploads</li>': '<li>장학금 신청 사진 업로드</li>',
    '<li>Government document submissions with size restrictions</li>': '<li>크기 제한이 있는 정부 문서 제출</li>',
    '<li>Job application forms and HR portal uploads</li>': '<li>입사 지원서 및 인사 포털 업로드</li>',
    '<li>Online course assignments and submissions</li>': '<li>온라인 코스 과제 및 제출</li>',
    '<li>Web form entries with file size limits</li>': '<li>파일 크기 제한이 있는 웹 양식 항목</li>',
    'Use PicEte Image Compressor Free →': '무료 PicEte 이미지 압축기 사용하기 →',
    'Free • No signup • Private browser-based processing': '무료 • 가입 불필요 • 비공개 브라우저 기반 처리',
    '<h3 style="font-size: 1.125rem; margin-bottom: 1rem; color: var(--text-color);">Related Compression Options</h3>': '<h3 style="font-size: 1.125rem; margin-bottom: 1rem; color: var(--text-color);">관련 압축 옵션</h3>',
    '<h4 style="font-size: 1rem; margin-bottom: 0.5rem;">Other File Size Targets</h4>': '<h4 style="font-size: 1rem; margin-bottom: 0.5rem;">다른 파일 크기 목표</h4>',
    '<li><a href="../compress-image-to-100kb/">Compress to 100KB</a> — Stricter limit</li>': '<li><a href="../compress-image-to-100kb/">100KB로 압축</a> — 더 엄격한 제한</li>',
    '<li><a href="../compress-image-to-500kb/">Compress to 500KB</a> — Higher quality</li>': '<li><a href="../compress-image-to-500kb/">500KB로 압축</a> — 더 높은 품질</li>',
    '<li><a href="../compress-image/">General Compressor</a> — Custom size</li>': '<li><a href="../compress-image/">일반 압축기</a> — 맞춤형 크기</li>',
    '<h2 class="section-title">Frequently Asked Questions</h2>': '<h2 class="section-title">자주 묻는 질문</h2>',
    '<summary class="faq-question">How do I compress an image to under 200KB?</summary>': '<summary class="faq-question">이미지를 어떻게 200KB 미만으로 압축하나요?</summary>',
    '<p class="faq-answer">Upload your image to PicEte and use the quality slider to find the right balance. For a 1920x1080 photo, 50-70% quality typically lands under 200KB. Smaller images like 800x600 can use 70-85% quality. The tool shows the output file size in real time, so adjust the slider until you hit the 200KB target.</p>': '<p class="faq-answer">PicEte에 이미지를 업로드하고 품질 슬라이더를 사용하여 적절한 균형을 찾으세요. 1920x1080 사진의 경우 보통 50-70% 품질이 200KB 미만이 됩니다. 800x600과 같은 작은 이미지는 70-85% 품질을 사용할 수 있습니다. 도구가 출력 파일 크기를 실시간으로 보여주므로 200KB 목표치에 도달할 때까지 슬라이더를 조정하세요.</p>',
    '<summary class="faq-question">Why do I need to compress images to 200KB?</summary>': '<summary class="faq-question">왜 이미지를 200KB로 압축해야 하나요?</summary>',
    '<p class="faq-answer">200KB is a common file size limit for document uploads, scholarship applications, job portals, and some content management systems. Many online forms reject images larger than 200KB to reduce server load. Compressing your images ensures they\'ll be accepted while maintaining enough quality for most uses.</p>': '<p class="faq-answer">200KB는 문서 업로드, 장학금 신청, 취업 포털 및 일부 콘텐츠 관리 시스템에서 흔히 사용되는 파일 크기 제한입니다. 많은 온라인 양식은 서버 부하를 줄이기 위해 200KB보다 큰 이미지를 거부합니다. 이미지를 압축하면 대부분의 용도에 충분한 품질을 유지하면서 이미지가 허용되도록 보장할 수 있습니다.</p>',
    '<summary class="faq-question">Will compressing to 200KB lose image quality?</summary>': '<summary class="faq-question">200KB로 압축하면 이미지 품질이 저하되나요?</summary>',
    '<p class="faq-answer">Some quality loss is inevitable when compressing to 200KB, but PicEte uses smart JPEG compression that minimizes visible artifacts. At 200KB, most photos look excellent on screens and print well up to 5x7 inches. For critical applications like professional printing, consider whether a higher file size limit is available.</p>': '<p class="faq-answer">200KB로 압축할 때 어느 정도의 품질 저하는 피할 수 없지만, PicEte는 눈에 지는 아티팩트를 최소화하는 스마트 JPEG 압축을 사용합니다. 200KB에서는 대부분의 사진이 화면에서 훌륭하게 보이며 최대 5x7인치까지 잘 인쇄됩니다. 전문 인쇄와 같은 중요한 작업의 경우 더 높은 파일 크기 제한이 가능한지 고려해 보세요.</p>',
    '<summary class="faq-question">Can I batch compress images to 200KB?</summary>': '<summary class="faq-question">여러 이미지를 한 번에 200KB로 일괄 압축할 수 있나요?</summary>',
    '<p class="faq-answer">Yes. Upload multiple images and the tool processes them all simultaneously. Since each image needs different compression levels to hit 200KB, you may need to adjust the quality slider for each one. Preview the results before downloading to ensure quality meets your needs.</p>': '<p class="faq-answer">네. 여러 이미지를 업로드하면 도구가 동시에 모두 처리합니다. 200KB에 맞추기 위해 각 이미지마다 다른 압축 수준이 필요하므로 각 이미지에 대해 품질 슬라이더를 조정해야 할 수 있습니다. 다운로드하기 전에 결과를 미리 확인하여 품질이 요구 사항을 충족하는지 확인하세요.</p>',
    '<h4>More Tools</h4>': '<h4>더 많은 도구</h4>',
    '<li><a href="../compress-image/">Image Compressor</a></li>': '<li><a href="../compress-image/">이미지 압축기</a></li>',
    '<li><a href="../resize-image/">Image Resizer</a></li>': '<li><a href="../resize-image/">이미지 크기 조절기</a></li>',
    '<li><a href="../png-to-jpg/">PNG to JPG</a></li>': '<li><a href="../png-to-jpg/">PNG를 JPG로</a></li>',
    '<li><a href="../webp-to-png/">WebP to PNG</a></li>': '<li><a href="../webp-to-png/">WebP를 PNG로</a></li>',
    '<h4>About</h4>': '<h4>소개</h4>',
    '<li><a href="../">Back to Home</a></li>': '<li><a href="../">홈으로 돌아가기</a></li>',
    '<li><a href="/privacy-policy.html">Privacy Policy</a></li>': '<li><a href="/privacy-policy.html">개인정보 처리방침</a></li>',
    '<h4>Partner Sites</h4>': '<h4>파트너 사이트</h4>',
    '<li><a href="https://mockupshot.online/">MockupShot - Screenshot Mockup</a></li>': '<li><a href="https://mockupshot.online/">MockupShot - 스크린샷 목업</a></li>',
    '<li><a href="https://ilovepalette.com/">ILovePalette - Color Tools</a></li>': '<li><a href="https://ilovepalette.com/">ILovePalette - 색상 도구</a></li>',
    '<p>© 2024 PicEte. All rights reserved.</p>': '<p>© 2024 PicEte. 모든 권리 보유.</p>'
}

process_file(r'd:\knowledge-base\06项目\哥飞建站\picete\ko\compress-image-to-100kb\index.html', r100)
process_file(r'd:\knowledge-base\06项目\哥飞建站\picete\ko\compress-image-to-200kb\index.html', r200)

print("Translation successful")

