var Vips=(()=>{var _scriptName=globalThis.document?.currentScript?.src;return async function(moduleArg={}){var moduleRtn;var h=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,p=ba&&"em-pthread"==globalThis.name;h.dynamicLibraries=h.dynamicLibraries||["vips-jxl.wasm","vips-heif.wasm"];h.workaroundCors&&(h.mainScriptUrlOrBlob=h.mainScriptUrlOrBlob||URL.createObjectURL(new Blob([`importScripts('${_scriptName}');`],{type:"application/javascript"})));var ca=[],da="./this.program";ba&&(_scriptName=self.location.href);var ea="";function fa(a){return h.locateFile?h.locateFile(a,ea):ea+a}var ha,ia;
if(aa||ba){try{ea=(new URL(".",_scriptName)).href}catch{}ba&&(ia=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ha=async a=>{a=await fetch(a,{credentials:"same-origin"});if(a.ok)return a.arrayBuffer();throw Error(a.status+" : "+a.url);}}var ja=console.log.bind(console),t=console.error.bind(console),ka=[],la,ma,oa=!1,pa;function w(){qa.buffer!=y.buffer&&ra()}var sa,ta,ua={},va;
if(p){var wa=!1;self.onunhandledrejection=b=>{throw b.reason||b;};function a(b){try{var c=b.data,d=c.V;if("load"===d){let e=[];self.onmessage=f=>e.push(f);va=()=>{postMessage({V:"loaded"});for(let f of e)a(f);self.onmessage=a};ka=c.Gb;ua=c.pc;for(const f of c.Sb)if(!h[f]||h[f].proxy)h[f]=(...g)=>{postMessage({V:"callHandler",Rb:f,Ab:g})},"print"==f&&(ja=h[f]),"printErr"==f&&(t=h[f]);qa=c.vc;ra();ma=c.wc;ya();za()}else if("run"===d){Aa(c.X);Ba(c.X,0,0,1,0,0);Ca();Da(c.X);wa||(Ea(),wa=!0);try{Fa(c.sc,
c.Ea)}catch(e){if("unwind"!=e)throw e;}}else"setimmediate"!==c.target&&("checkMailbox"===d?wa&&Ga():d&&(t(`worker: received unknown command ${d}`),t(c)))}catch(e){throw Ha(),e;}}self.onmessage=a}var Ia=!1,Ja=!1;function ra(){var a=qa.buffer;y=new Int8Array(a);z=new Int16Array(a);A=new Uint8Array(a);F=new Uint16Array(a);G=new Int32Array(a);H=new Uint32Array(a);Ka=new Float32Array(a);La=new Float64Array(a);I=new BigInt64Array(a);Ma=new BigUint64Array(a)}var Na=[];
function Oa(){Ia=!0;p?va():(Pa(Na),h.noFSInit||FS.Ia||FS.init(),Qa.__wasm_call_ctors(),Pa(Ra),FS.fb=!1)}function J(a){h.onAbort?.(a);a=`Aborted(${a})`;t(a);oa=!0;a+=". Build with -sASSERTIONS for more info.";Ia&&Sa();a=new WebAssembly.RuntimeError(a);ta?.(a);throw a;}var Ta;async function Ua(a){if(!la)try{var b=await ha(a);return new Uint8Array(b)}catch{}if(a==Ta&&la)a=new Uint8Array(la);else if(ia)a=ia(a);else throw"both async and sync fetching of the wasm failed";return a}
async function Va(a,b){try{var c=await Ua(a);return await WebAssembly.instantiate(c,b)}catch(d){t(`failed to asynchronously prepare wasm: ${d}`),J(d)}}async function Wa(a){var b=Ta;if(!la)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){t(`wasm streaming compile failed: ${d}`),t("falling back to ArrayBuffer instantiation")}return Va(b,a)}
function Xa(){L={__assert_fail:Ya,__call_sighandler:Za,__lsan_ignore_object:$a,__pthread_create_js:bb,__syscall_dup:cb,__syscall_faccessat:db,__syscall_fcntl64:eb,__syscall_fstat64:fb,__syscall_ftruncate64:gb,__syscall_getcwd:hb,__syscall_ioctl:ib,__syscall_lstat64:jb,__syscall_newfstatat:kb,__syscall_openat:lb,__syscall_poll:mb,__syscall_rmdir:nb,__syscall_stat64:ob,__syscall_unlinkat:pb,__throw_exception_with_stack_trace:qb,_abort_js:rb,_dlopen_js:sb,_dlsym_catchup_js:tb,_dlsym_js:ub,_embind_finalize_value_object:vb,
_embind_register_arithmetic_vector:wb,_embind_register_bigint:xb,_embind_register_bool:Ab,_embind_register_class:Bb,_embind_register_class_class_function:Cb,_embind_register_class_constructor:Db,_embind_register_class_function:Eb,_embind_register_class_property:Fb,_embind_register_emval:Gb,_embind_register_enum:Hb,_embind_register_enum_value:Ib,_embind_register_float:Jb,_embind_register_function:Kb,_embind_register_integer:Lb,_embind_register_iterable:Mb,_embind_register_memory_view:Nb,_embind_register_optional:Ob,
_embind_register_std_string:Pb,_embind_register_std_wstring:Qb,_embind_register_value_object:Rb,_embind_register_value_object_field:Sb,_embind_register_void:Tb,_emscripten_dlopen_js:Ub,_emscripten_dlsync_threads:Vb,_emscripten_get_dynamic_libraries_js:Wb,_emscripten_init_main_thread_js:Xb,_emscripten_notify_mailbox_postmessage:Yb,_emscripten_receive_on_main_thread_js:Zb,_emscripten_runtime_keepalive_clear:$b,_emscripten_thread_cleanup:ac,_emscripten_thread_exit_joinable:bc,_emscripten_thread_mailbox_await:Da,
_emscripten_thread_set_strongref:cc,_emval_array_to_memory_view:dc,_emval_create_invoker:ec,_emval_decref:fc,_emval_get_global:gc,_emval_get_module_property:hc,_emval_get_property:ic,_emval_incref:jc,_emval_instanceof:kc,_emval_invoke:lc,_emval_is_number:mc,_emval_is_string:nc,_emval_new_cstring:oc,_emval_run_destructors:pc,_emval_set_property:qc,_emval_typeof:rc,_gmtime_js:sc,_localtime_js:tc,_mktime_js:uc,_mmap_js:vc,_munmap_js:wc,_tzset_js:xc,clock_time_get:yc,emscripten_check_blocking_allowed:zc,
emscripten_date_now:Ac,emscripten_err:Bc,emscripten_exit_with_live_runtime:Cc,emscripten_get_heap_max:Dc,emscripten_get_now:Ec,emscripten_num_logical_cores:Fc,emscripten_promise_destroy:Gc,emscripten_promise_resolve:Hc,emscripten_resize_heap:Ic,environ_get:Jc,environ_sizes_get:Kc,exit:Lc,fd_close:Mc,fd_fdstat_get:Nc,fd_read:Oc,fd_seek:Pc,fd_write:Qc,ffi_call_js:Rc,heif_error_success:Sc,memory:qa,proc_exit:Tc,random_get:Uc};var a=new Proxy(new Set(["__lsan_ignore_object"]),Vc);return{env:L,wasi_snapshot_preview1:L,
"GOT.mem":a,"GOT.func":a}}
async function ya(){function a(d,e){var f=Qa=d.exports;Wc(Qa);var g=Xc(e);Yc(Qa._emscripten_tls_init,d.exports,g);d=Qa;Zc=d.pthread_self;$c=d.malloc;h._main=d.main;M=d.free;ad=d.fflush;bd=d.calloc;h.__ZnamSt11align_val_t=d._ZnamSt11align_val_t;cd=d.__getTypeName;Ea=d._embind_initialize_bindings;h._emscripten_builtin_free=d.emscripten_builtin_free;dd=d.emscripten_builtin_memalign;h._emscripten_builtin_malloc=d.emscripten_builtin_malloc;ed=d.__funcs_on_exit;h.___libc_calloc=d.__libc_calloc;h.___libc_free=
d.__libc_free;h.___libc_malloc=d.__libc_malloc;fd=d.__dl_seterr;gd=d._emscripten_dlsync_self_async;hd=d._emscripten_dlsync_self;jd=d._emscripten_proxy_dlsync_async;kd=d._emscripten_proxy_dlsync;ld=d._emscripten_find_dylib;Ba=d._emscripten_thread_init;md=d.__set_thread_state;Ha=d._emscripten_thread_crashed;nd=d._emscripten_run_js_on_main_thread_done;od=d._emscripten_run_js_on_main_thread;pd=d._emscripten_thread_free_data;qd=d._emscripten_thread_exit;h._strndup=d.strndup;rd=d._emscripten_check_mailbox;
h.__ZdaPvm=d._ZdaPvm;h.___libc_realloc=d.__libc_realloc;h._emscripten_builtin_calloc=d.emscripten_builtin_calloc;h._emscripten_builtin_realloc=d.emscripten_builtin_realloc;h._malloc_size=d.malloc_size;h._malloc_usable_size=d.malloc_usable_size;h._reallocf=d.reallocf;sd=d.emscripten_get_sbrk_ptr;Sa=d.__trap;td=d.emscripten_stack_set_limits;ud=d._emscripten_stack_restore;vd=d._emscripten_stack_alloc;wd=d.emscripten_stack_get_current;xd=d.__thrown_object_from_unwind_exception;yd=d.__get_exception_message;
N=d.__indirect_function_table;zd=d.__cpp_exception;Ad=d.__heap_base.value;Bd(f);Cd("__main__",0,L);Dd();ma=e;return Qa}var b=Xa();if(h.instantiateWasm)return new Promise(d=>{h.instantiateWasm(b,(e,f)=>{d(a(e,f))})});if(p){var c=new WebAssembly.Instance(ma,Xa());return a(c,ma)}Ta??=fa("vips.wasm");return function(d){return a(d.instance,d.module)}(await Wa(b))}var Fd=a=>{if(!(a instanceof Ed||"unwind"==a))throw a;};
class Ed{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var O=0,Gd=a=>{a.terminate();a.onmessage=()=>{}},Md=a=>{var b=Hd[a];Id.delete(a);a in Jd&&Jd[a].resolve();a=b.X;delete Hd[a];Kd.push(b);Ld.splice(Ld.indexOf(b),1);b.X=0;pd(a)},Pa=a=>{for(;0<a.length;)a.shift()(h)},Nd=[],Od=a=>{Id.add(a);a in Jd&&Jd[a].resolve()},Pd=0,Qd=null,Rd=()=>{Pd--;h.monitorRunDependencies?.(Pd);if(0==Pd&&Qd){var a=Qd;Qd=null;a()}},Sd=()=>{Pd++;h.monitorRunDependencies?.(Pd)},Vd=a=>{0==Kd.length&&(Td(),Ud(Kd[0]));var b=Kd.pop();if(!b)return 6;Ld.push(b);Hd[a.X]=b;b.X=a.X;b.postMessage({V:"run",
sc:a.rc,Ea:a.Ea,X:a.X},a.tb);return 0},Wd=!Atomics.waitAsync||globalThis.navigator?.userAgent&&91>Number((navigator.userAgent.match(/Chrom(e|ium)\/([0-9]+)\./)||[])[2]),Kd=[],Ld=[],Xd=[],Hd={};function Yd(){for(var a=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;a--;)Td();Nd.push(async()=>{var b=Zd();Sd("loading-workers");await b;Rd("loading-workers")});Jd={};Id=new Set}var $d=()=>{for(var a of Ld)Gd(a);for(a of Kd)Gd(a);Kd=[];Ld=[];Hd={}};function Ca(){Xd.forEach(a=>a())}
var Ud=a=>new Promise(b=>{a.onmessage=f=>{var g=f.data;f=g.V;if(g.Da&&g.Da!=Zc()){var k=Hd[g.Da];k?k.postMessage(g,g.tb):t(`worker sent message (${f}) to pthread (${g.Da}) that no longer exists`)}else if("checkMailbox"===f)Ga();else if("spawnThread"===f)Vd(g);else if("cleanupThread"===f)ae(()=>Md(g.Ua));else if("markAsFinished"===f)Od(g.Ua);else if("loaded"===f)a.loaded=!0,b(a);else if("setimmediate"===g.target)a.postMessage(g);else if("callHandler"===f)h[g.Rb](...g.Ab);else f&&t(`worker sent an unknown command ${f}`)};
a.onerror=f=>{t(`${"worker sent an error!"} ${f.filename}:${f.lineno}: ${f.message}`);throw f;};var c=[],d=["onExit","onAbort","print","printErr"],e;for(e of d)h.propertyIsEnumerable(e)&&c.push(e);a.postMessage({V:"load",Sb:c,vc:qa,wc:ma,Gb:ka,pc:ua})});async function Zd(){if(!p)return Promise.all(Kd.map(Ud))}function Td(){var a=_scriptName;h.mainScriptUrlOrBlob&&(a=h.mainScriptUrlOrBlob,"string"!=typeof a&&(a=URL.createObjectURL(a)));a=new Worker(a,{name:"em-pthread"});Kd.push(a)}
var Id,Jd,be,P=(a,b,...c)=>{var d=16*c.length,e=wd(),f=vd(d),g=f>>3,k;for(k of c)"bigint"==typeof k?((w(),I)[g++]=1n,(w(),I)[g++]=k):((w(),I)[g++]=0n,(w(),La)[g++]=k);a=od(a,0,d,f,b);ud(e);return a};function Tc(a){if(p)return P(0,1,a);pa=a;ce||0<O||($d(),h.onExit?.(a),oa=!0);throw new Ed(a);}Tc.g="vi";function de(a){if(p)return P(1,0,a);Lc(a)}
var Lc=a=>{pa=a;if(p)throw de(a),"unwind";if(!(ce||0<O||p)){ed();FS.Ia=!1;ad(0);for(var b of FS.streams)b&&FS.close(b);$d();b=Zc();md(0,0,0,1);Wd||Atomics.notify((w(),G),b>>2);Ja=!0}Tc(a)};Lc.g="vi";var ae=a=>{if(!Ja&&!oa)try{a()}catch(b){Fd(b)}finally{if(!(Ja||ce||0<O))try{p?Zc()&&qd(pa):Lc(pa)}catch(b){Fd(b)}}},ee=a=>{O+=1;setTimeout(()=>{--O;ae(a)},1E4)},fe=[],ge={},he=!1;
function ie(){function a(){he=document.pointerLockElement===h.canvas}if(!je){je=!0;fe.push({canHandle:c=>!h.noImageDecoding&&/\.(jpg|jpeg|png|bmp|webp)$/i.test(c),handle:async(c,d)=>{var e=new Blob([c],{type:ke(d)});e.size!==c.length&&(e=new Blob([(new Uint8Array(c)).buffer],{type:ke(d)}));var f=URL.createObjectURL(e);return new Promise((g,k)=>{var l=new Image;l.onload=()=>{var m=document.createElement("canvas");m.width=l.width;m.height=l.height;m.getContext("2d").drawImage(l,0,0);URL.revokeObjectURL(f);
g(c)};l.onerror=()=>{t(`Image ${f} could not be decoded`);k()};l.src=f})}});fe.push({canHandle:c=>!h.noAudioDecoding&&c.slice(-4)in{".ogg":1,".wav":1,".mp3":1},handle:async(c,d)=>new Promise(e=>{function f(){g||(g=!0,e(c))}var g=!1,k=URL.createObjectURL(new Blob([c],{type:ke(d)})),l=new Audio;l.addEventListener("canplaythrough",()=>f(l),!1);l.onerror=()=>{if(!g){t(`warning: browser could not fully decode audio ${d}, trying slower base64 approach`);for(var m="",n=0,r=0,u=0;u<c.length;u++)for(n=n<<
8|c[u],r+=8;6<=r;){var q=n>>r-6&63;r-=6;m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[q]}2==r?(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&3)<<4],m+="=="):4==r&&(m+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(n&15)<<2],m+="=");l.src="data:audio/x-"+d.slice(-3)+";base64,"+m;f(l)}};l.src=k;ee(()=>{f(l)})})});var b=h.canvas;b&&(document.addEventListener("pointerlockchange",a,!1),h.elementPointerLock&&b.addEventListener("click",
c=>{!he&&h.canvas.requestPointerLock&&(h.canvas.requestPointerLock(),c.preventDefault())},!1))}}function ke(a){return{jpg:"image/jpeg",jpeg:"image/jpeg",png:"image/png",bmp:"image/bmp",ogg:"audio/ogg",wav:"audio/wav",mp3:"audio/mpeg"}[a.slice(a.lastIndexOf(".")+1)]}var le={},je,me={},Vc={get(a,b){var c=me[b];c||=me[b]=new WebAssembly.Global({value:"i32",mutable:!0},-1);a.has(b)||(c.required=!0);return c}},z,G,I,y,Ka,La,F,H,Ma,A,ne=[];
function Aa(a){var b=(w(),H)[a+48>>2];a=(w(),H)[a+52>>2];td(b,b-a);ud(b)}
var oe=new TextDecoder,pe=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},qe=(a,b=0,c)=>{c=pe(a,b,c);return oe.decode(a.buffer?a.buffer instanceof ArrayBuffer?a.subarray(b,c):a.slice(b,c):new Uint8Array(a.slice(b,c)))},Xc=a=>{function b(){for(var r=0,u=1;;){var q=a[f++];r+=(q&127)*u;u*=128;if(!(q&128))break}return r}function c(){var r=b();f+=r;return qe(a,f-r,r)}function d(){for(var r=b(),u=[];r--;)u.push(c());return u}function e(r,u){if(r)throw Error(u);}var f=0,g=0;if(a instanceof
WebAssembly.Module)g=WebAssembly.Module.customSections(a,"dylink.0"),e(0===g.length,"need dylink section"),a=new Uint8Array(g[0]),g=a.length;else{g=1836278016==(new Uint32Array((new Uint8Array(a.subarray(0,24))).buffer))[0];e(!g,"need to see wasm magic number");e(0!==a[8],"need the dylink section to be first");f=9;g=b();g=f+g;var k=c();e("dylink.0"!==k)}for(k={Oa:[],sb:new Set,vb:new Set,pb:[]};f<g;){var l=a[f++],m=b();if(1===l)k.Na=b(),k.$b=b(),k.ta=b(),k.Qc=b();else if(2===l)k.Oa=d();else if(3===
l)for(l=b();l--;){m=c();var n=b();n&256&&k.sb.add(m)}else if(4===l)for(l=b();l--;)c(),m=c(),n=b(),1==(n&3)&&k.vb.add(m);else 5===l?k.pb=d():f+=m}return k},Fa=(a,b)=>{ce=O=0;hd();a=N.get(a)(b);ce||0<O?pa=a:qd(a)},Cd=(a,b,c)=>{c={Aa:Infinity,name:a,exports:c,global:!0};re[a]=c;void 0!=b&&(se[b]=c);return c},re={},se={},te=(a,b)=>Math.ceil(a/b)*b,ue=a=>{if(Ia)return bd(a,1);var b=Ad;Ad=a=b+16*Math.ceil(a/16);if(!p){var c=sd();(w(),H)[c>>2]=a}return b},we=(a,b)=>{if(ve)for(var c=a;c<a+b;c++){var d=N.get(c);
d&&ve.set(d,c)}},ve,xe=a=>{ve||(ve=new WeakMap,we(0,N.length));return ve.get(a)||0},ye=[],ze=a=>{const b=a.length;return[b%128|128,b>>7,...a]},Ae={i:127,p:127,j:126,f:125,d:124,e:111},Be=a=>ze(Array.from(a,b=>Ae[b])),Ce=(a,b)=>{var c=xe(a);if(c)return c;c=ye.length?ye.pop():N.grow(1);try{N.set(c,a)}catch(d){if(!(d instanceof TypeError))throw d;b=Uint8Array.of(0,97,115,109,1,0,0,0,1,...ze([1,96,...Be(b.slice(1)),...Be("v"===b[0]?"":b[0])]),2,7,1,1,101,1,102,0,0,7,5,1,1,102,0,0);b=new WebAssembly.Module(b);
b=(new WebAssembly.Instance(b,{e:{f:a}})).exports.f;N.set(c,b)}ve.set(a,c);return c},Bd=(a,b)=>{for(var c in a){var d=c;if(!"memory __memory_base __table_base __stack_pointer __indirect_function_table __cpp_exception __c_longjmp __wasm_apply_data_relocs __dso_handle __tls_size __tls_align __set_stack_limits _emscripten_tls_init __wasm_init_tls __wasm_call_ctors __start_em_asm __stop_em_asm __start_em_js __stop_em_js".split(" ").includes(d)&&!d.startsWith("__em_js__")){d=a[c];var e=me[c]&&-1!=me[c].value;
if(b||!e){if("function"==typeof d)d=Ce(d);else if("number"!=typeof d.value)continue;let f;me[f=c]??(me[f]=new WebAssembly.Global({value:"i32",mutable:!0}));me[c].value=d}}}},De=(a,b=0)=>{var c={},d;for(d in a){var e=d;var f=a[d];a:{if(f instanceof WebAssembly.Global)try{f.value=f.value}catch{var g=!0;break a}g=!1}f=g?new WebAssembly.Global({value:"i32"},f.value+b):f;c[e]=f}return c},Ee=a=>{a=L[a];return!a||a.Ba?!1:!0},Fe=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ge=a=>{var b;Ee(a)&&(b=L[a]);
return{Ta:b,name:a}},Ra=[],Q=(a,b,c)=>{if(!a)return"";b=pe((w(),A),a,b,c);return oe.decode((w(),A).slice(a,b))},Le=(a,b,c,d,e)=>{function f(){function l(C,B){function E(xa,Z){xa=[];for(var yb=0;;yb++){var ab="$"+yb;if(!Z.includes(ab))break;xa.push(ab)}xa=xa.join(",");He[D]=eval(`(${xa}) => { ${Z} };`)}function K(xa,Z,yb){var ab=[];Z=Z.slice(1,-1);if("void"!=Z){Z=Z.split(",");for(var Dg of Z)Z=Dg.split(" ").pop(),ab.push(Z.replaceAll("*",""))}q[xa]=eval(`(${ab}) => ${yb};`)}!p&&c&&(ua[c]=C);we(u,g.ta);
q=De(B.exports,r);Bd(q);b.zb||Ie();if("__start_em_asm"in q){var D=q.__start_em_asm.value;for(C=q.__stop_em_asm.value;D<C;){var na=Q(D);E(D,na);D=(w(),A).indexOf(0,D)+1}}for(var zb in q)if(zb.startsWith("__em_js__")){D=q[zb].value;na=Q(D);var [Eg,Fg]=na.split("<::>");K(zb.replace("__em_js__",""),Eg,Fg);delete q[zb]}Yc(q._emscripten_tls_init,B.exports,g);m&&((B=q.__wasm_apply_data_relocs)&&(Ia?B():Na.push(B)),(B=q.__wasm_call_ctors)&&(Ia?B():Ra.push(B)));return q}var m=!e||!(w(),y)[e+8];if(m){var n=
Math.pow(2,g.$b),r=g.Na?te(ue(g.Na+n),n):0,u=g.ta?N.length:0;e&&((w(),y)[e+8]=1,(w(),H)[e+12>>2]=r,(w(),G)[e+16>>2]=g.Na,(w(),H)[e+20>>2]=u,(w(),G)[e+24>>2]=g.ta)}else r=(w(),H)[e+12>>2],u=(w(),H)[e+20>>2];g.ta&&N.grow(g.ta);var q;n=new Proxy({},{get(C,B){switch(B){case "__memory_base":return r;case "__table_base":return u}if(B in L&&!L[B].Ba)return L[B];if(!(B in C)){var E;C[B]=(...K)=>{if(!E){var D=Ge(B).Ta;!D&&d&&(D=d[B]);D||=q[B];E=D}return E(...K)}}return C[B]}});var v=new Proxy(g.vb,Vc),x={"GOT.mem":v,
"GOT.func":v,env:n,wasi_snapshot_preview1:n};if(b.I)return(async()=>{var C;a instanceof WebAssembly.Module?C=new WebAssembly.Instance(a,x):{module:a,instance:C}=await WebAssembly.instantiate(a,x);return l(a,C)})();n=a instanceof WebAssembly.Module?a:new WebAssembly.Module(a);v=new WebAssembly.Instance(n,x);return l(n,v)}var g=Xc(a);b={...b,Sa:{ec:c,ic:g.pb}};if(b.I)return g.Oa.reduce((l,m)=>l.then(()=>{m=Je(m,b.Sa)??m;return Ke(m,b,d)}),Promise.resolve()).then(f);for(var k of g.Oa)k=Je(k,b.Sa)??k,
Ke(k,b,d);return f()},Wc=a=>{var b,c;for([b,c]of Object.entries(a))Ee(b)||(L[b]=c)},Me=async a=>{a=await ha(a);return new Uint8Array(a)},Ne=(a,b)=>{for(var c=0,d=a.length-1;0<=d;d--){var e=a[d];"."===e?a.splice(d,1):".."===e?(a.splice(d,1),c++):c&&(a.splice(d,1),c--)}if(b)for(;c;c--)a.unshift("..");return a},Oe=a=>{var b="/"===a.charAt(0),c="/"===a.slice(-1);(a=Ne(a.split("/").filter(d=>!!d),!b).join("/"))||b||(a=".");a&&c&&(a+="/");return(b?"/":"")+a},Pe=a=>{var b=/^(\/?|)([\s\S]*?)((?:\.{1,2}|[^\/]+?|)(\.[^.\/]*|))(?:[\/]*)$/.exec(a).slice(1);
a=b[0];b=b[1];if(!a&&!b)return".";b&&=b.slice(0,-1);return a+b},Qe=a=>a&&a.match(/([^\/]+|\/)\/*$/)[1],Re=(a,b)=>Oe(a+"/"+b),Se=a=>{var b=wd();a=a();ud(b);return a},Te=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Ue=(a,b,c,d)=>{if(!(0<d))return 0;var e=c;d=c+d-1;for(var f=0;f<a.length;++f){var g=a.codePointAt(f);if(127>=g){if(c>=d)break;b[c++]=g}else if(2047>=g){if(c+1>=d)break;b[c++]=192|g>>6;b[c++]=128|g&63}else if(65535>=
g){if(c+2>=d)break;b[c++]=224|g>>12;b[c++]=128|g>>6&63;b[c++]=128|g&63}else{if(c+3>=d)break;b[c++]=240|g>>18;b[c++]=128|g>>12&63;b[c++]=128|g>>6&63;b[c++]=128|g&63;f++}}b[c]=0;return c-e},Ve=(a,b,c)=>Ue(a,(w(),A),b,c),We=a=>{var b=Te(a)+1,c=vd(b);Ve(a,c,b);return c},Xe=()=>a=>(a.set(crypto.getRandomValues(new Uint8Array(a.byteLength))),0),Ye=a=>(Ye=Xe())(a),Ze=(...a)=>{for(var b="",c=!1,d=a.length-1;-1<=d&&!c;d--){c=0<=d?a[d]:FS.cwd();if("string"!=typeof c)throw new TypeError("Arguments to path.resolve must be strings");
if(!c)return"";b=c+"/"+b;c="/"===c.charAt(0)}b=Ne(b.split("/").filter(e=>!!e),!c).join("/");return(c?"/":"")+b||"."},$e=(a,b)=>{function c(g){for(var k=0;k<g.length&&""===g[k];k++);for(var l=g.length-1;0<=l&&""===g[l];l--);return k>l?[]:g.slice(k,l-k+1)}a=Ze(a).slice(1);b=Ze(b).slice(1);a=c(a.split("/"));b=c(b.split("/"));for(var d=Math.min(a.length,b.length),e=d,f=0;f<d;f++)if(a[f]!==b[f]){e=f;break}d=[];for(f=e;f<a.length;f++)d.push("..");d=d.concat(b.slice(e));return d.join("/")},af=[],bf=a=>{var b=
Array(Te(a)+1);a=Ue(a,b,0,b.length);b.length=a;return b},cf=[];function df(a,b){cf[a]={input:[],output:[],ea:b};FS.registerDevice(a,ef)}
var ef={open(a){var b=cf[a.node.ra];if(!b)throw new FS.h(43);a.C=b;a.seekable=!1},close(a){a.C.ea.xa(a.C)},xa(a){a.C.ea.xa(a.C)},read(a,b,c,d){if(!a.C||!a.C.ea.eb)throw new FS.h(60);for(var e=0,f=0;f<d;f++){try{var g=a.C.ea.eb(a.C)}catch(k){throw new FS.h(29);}if(void 0===g&&0===e)throw new FS.h(6);if(null===g||void 0===g)break;e++;b[c+f]=g}e&&(a.node.$=Date.now());return e},write(a,b,c,d){if(!a.C||!a.C.ea.Qa)throw new FS.h(60);try{for(var e=0;e<d;e++)a.C.ea.Qa(a.C,b[c+e])}catch(f){throw new FS.h(29);
}d&&(a.node.O=a.node.N=Date.now());return e}},ff={eb(){a:{if(!af.length){var a=null;globalThis.window?.prompt&&(a=window.prompt("Input: "),null!==a&&(a+="\n"));if(!a){a=null;break a}af=bf(a)}a=af.shift()}return a},Qa(a,b){null===b||10===b?(ja(qe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(ja(qe(a.output)),a.output=[])},Vb(){return{Cc:25856,Ec:5,Bc:191,Dc:35387,Ac:[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}},Wb(){return 0},Xb(){return[24,
80]}},gf={Qa(a,b){null===b||10===b?(t(qe(a.output)),a.output=[]):0!=b&&a.output.push(b)},xa(a){0<a.output?.length&&(t(qe(a.output)),a.output=[])}},hf=a=>{a=65536*Math.ceil(a/65536);var b=dd(65536,a);b&&(w(),A).fill(0,b,b+a);return b},R={W:null,mount(){return R.createNode(null,"/",16895,0)},createNode(a,b,c,d){var e;(e=FS.isBlkdev(c))||(e=4096===(c&61440));if(e)throw new FS.h(63);R.W||(R.W={dir:{node:{S:R.m.S,U:R.m.U,ia:R.m.ia,ca:R.m.ca,rename:R.m.rename,unlink:R.m.unlink,rmdir:R.m.rmdir,sa:R.m.sa,
symlink:R.m.symlink},stream:{llseek:R.o.llseek}},file:{node:{S:R.m.S,U:R.m.U},stream:{llseek:R.o.llseek,read:R.o.read,write:R.o.write,ja:R.o.ja,la:R.o.la}},link:{node:{S:R.m.S,U:R.m.U,readlink:R.m.readlink},stream:{}},Wa:{node:{S:R.m.S,U:R.m.U},stream:FS.Cb}});c=FS.createNode(a,b,c,d);FS.isDir(c.mode)?(c.m=R.W.dir.node,c.o=R.W.dir.stream,c.u={}):FS.isFile(c.mode)?(c.m=R.W.file.node,c.o=R.W.file.stream,c.L=0,c.u=R.Hb??(R.Hb=new Uint8Array(0))):FS.isLink(c.mode)?(c.m=R.W.link.node,c.o=R.W.link.stream):
FS.isChrdev(c.mode)&&(c.m=R.W.Wa.node,c.o=R.W.Wa.stream);c.$=c.O=c.N=Date.now();a&&(a.u[b]=c,a.$=a.O=a.N=c.$);return c},m:{S(a){var b={};b.Eb=FS.isChrdev(a.mode)?a.id:1;b.Ub=a.id;b.mode=a.mode;b.ac=1;b.uid=0;b.Qb=0;b.ra=a.ra;FS.isDir(a.mode)?b.size=4096:FS.isFile(a.mode)?b.size=a.L:FS.isLink(a.mode)?b.size=a.link.length:b.size=0;b.$=new Date(a.$);b.O=new Date(a.O);b.N=new Date(a.N);b.Bb=4096;b.Va=Math.ceil(b.size/b.Bb);return b},U(a,b){for(var c of["mode","atime","mtime","ctime"])null!=b[c]&&(a[c]=
b[c]);void 0!==b.size&&(b=b.size,a.L!=b&&(c=a.u,a.u=new Uint8Array(b),a.u.set(c.subarray(0,Math.min(b,a.L))),a.L=b))},ia(){R.Fa||(R.Fa=new FS.h(44),R.Fa.stack="<generic error, no stack>");throw R.Fa;},ca(a,b,c,d){return R.createNode(a,b,c,d)},rename(a,b,c){try{var d=jf(b,c)}catch(f){}if(d){if(FS.isDir(a.mode))for(var e in d.u)throw new FS.h(55);kf(d)}delete a.parent.u[a.name];b.u[c]=a;a.name=c;b.N=b.O=a.parent.N=a.parent.O=Date.now()},unlink(a,b){delete a.u[b];a.N=a.O=Date.now()},rmdir(a,b){var c=
jf(a,b),d;for(d in c.u)throw new FS.h(55);delete a.u[b];a.N=a.O=Date.now()},sa(a){return[".","..",...Object.keys(a.u)]},symlink(a,b,c){a=R.createNode(a,b,41471,0);a.link=c;return a},readlink(a){if(!FS.isLink(a.mode))throw new FS.h(28);return a.link}},o:{read(a,b,c,d,e){if(e>=a.node.L)return 0;d=Math.min(a.node.L-e,d);b.set(a.node.u.subarray(e,e+d),c);return d},write(a,b,c,d,e,f){b.buffer===(w(),y).buffer&&(f=!1);if(!d)return 0;a=a.node;a.O=a.N=Date.now();if(f)a.u=b.subarray(c,c+d),a.L=d;else if(0===
a.L&&0===e)a.u=b.slice(c,c+d),a.L=d;else{f=e+d;var g=a.u.length;g>=f||(f=Math.max(f,g*(1048576>g?2:1.125)>>>0),g&&(f=Math.max(f,256)),g=a.u.subarray(0,a.L),a.u=new Uint8Array(f),a.u.set(g));a.u.set(b.subarray(c,c+d),e);a.L=Math.max(a.L,e+d)}return d},llseek(a,b,c){1===c?b+=a.position:2===c&&FS.isFile(a.node.mode)&&(b+=a.node.L);if(0>b)throw new FS.h(28);return b},ja(a,b,c,d,e){if(!FS.isFile(a.node.mode))throw new FS.h(43);a=a.node.u;if(e&2||a.buffer!==(w(),y).buffer){d=!0;e=hf(b);if(!e)throw new FS.h(48);
if(a){if(0<c||c+b<a.length)a.subarray?a=a.subarray(c,c+b):a=Array.prototype.slice.call(a,c,c+b);(w(),y).set(a,e)}}else d=!1,e=a.byteOffset;return{A:e,fa:d}},la(a,b,c,d){R.o.write(a,b,0,d,c,!1);return 0}}},lf=a=>{"string"==typeof a&&(a=bf(a));a.subarray||(a=new Uint8Array(a));return a},mf=(a,b)=>{var c=0;a&&(c|=365);b&&(c|=146);return c},nf=async(a,b)=>{"undefined"!=typeof le&&ie();for(var c of fe)if(c.canHandle(b))return c.handle(a,b);return a},of=async(a,b,c,d,e,f,g,k)=>{var l=b?Ze(Oe(a+"/"+b)):
a,m=`cp ${l}`;Sd(m);try{var n=c;"string"==typeof c&&(n=await Me(c));n=await nf(n,l);k?.();f||FS.createDataFile(a,b,n,d,e,g)}finally{Rd(m)}};function jf(a,b){var c=FS.isDir(a.mode)?(c=pf(a,"x"))?c:a.m.ia?0:2:54;if(c)throw new FS.h(c);for(c=FS.da[qf(a.id,b)];c;c=c.ka){var d=c.name;if(c.parent.id===a.id&&d===b)return c}return FS.ia(a,b)}function kf(a){var b=qf(a.parent.id,a.name);if(FS.da[b]===a)FS.da[b]=a.ka;else for(b=FS.da[b];b;){if(b.ka===a){b.ka=a.ka;break}b=b.ka}}
function qf(a,b){for(var c=0,d=0;d<b.length;d++)c=(c<<5)-c+b.charCodeAt(d)|0;return(a+c>>>0)%FS.da.length}function rf(a){var b=qf(a.parent.id,a.name);a.ka=FS.da[b];FS.da[b]=a}function pf(a,b){return FS.fb?0:b.includes("r")&&!(a.mode&292)||b.includes("w")&&!(a.mode&146)||b.includes("x")&&!(a.mode&73)?2:0}function sf(a,b){if(!FS.isDir(a.mode))return 54;try{return jf(a,b),20}catch(c){}return pf(a,"wx")}
function tf(a,b,c){try{var d=jf(a,b)}catch(e){return e.B}if(a=pf(a,"wx"))return a;if(c){if(!FS.isDir(d.mode))return 54;if(FS.na(d)||FS.getPath(d)===FS.cwd())return 10}else if(FS.isDir(d.mode))return 31;return 0}function uf(a,b){if(!a)throw new FS.h(b);return a}function S(a){a=FS.cb(a);if(!a)throw new FS.h(8);return a}function vf(a,b=-1){a=Object.assign(new FS.xb,a);if(-1==b)a:{for(b=0;b<=FS.yb;b++)if(!FS.streams[b])break a;throw new FS.h(33);}a.aa=b;return FS.streams[b]=a}
function wf(a,b=-1){a=vf(a,b);a.o?.Gc?.(a);return a}function xf(a,b,c){var d=a?.o.U;a=d?a:b;d??=b.m.U;uf(d,63);try{d(a,c)}catch(e){if(e instanceof RangeError)throw new FS.h(22);throw e;}}function yf(a){var b=[];for(a=[a];a.length;){var c=a.pop();b.push(c);a.push(...c.oa)}return b}function zf(a){var b={zc:4096,Jc:4096,Va:1E6,yc:5E5,xc:5E5,files:FS.Pa,Hc:FS.Pa-1,Kc:42,flags:2,Nc:255};a.m.rb&&Object.assign(b,a.m.rb(a.mount.cc.root));return b}
function Af(a,b,c,d){xf(a,b,{mode:c&4095|b.mode&-4096,N:Date.now(),$a:d})}function Bf(a,b,c){if(FS.isDir(b.mode))throw new FS.h(31);if(!FS.isFile(b.mode))throw new FS.h(28);var d=pf(b,"w");if(d)throw new FS.h(d);xf(a,b,{size:c,timestamp:Date.now()})}function Cf(a,b,c,d){a="string"==typeof a?a:FS.getPath(a);b=Oe(a+"/"+b);return FS.create(b,mf(c,d))}
function Df(a){if(!(a.Yb||a.Zb||a.link||a.u))if(globalThis.XMLHttpRequest)J("Lazy loading should have been performed (contents set) in createLazyFile, but it was not. Lazy loading only works in web workers. Use --embed-file or --preload-file in emcc on the main thread.");else try{a.u=ia(a.url)}catch(b){throw new FS.h(29);}}
var FS={root:null,oa:[],Za:{},streams:[],Pa:1,da:null,Xa:"/",Ia:!1,fb:!0,Kb:null,Ca:0,h:class{name="ErrnoError";constructor(a){this.B=a}},xb:class{P={};node=null;get object(){return this.node}set object(a){this.node=a}get flags(){return this.P.flags}set flags(a){this.P.flags=a}get position(){return this.P.position}set position(a){this.P.position=a}},wb:class{m={};o={};T=null;constructor(a,b,c,d){a||=this;this.parent=a;this.mount=a.mount;this.id=FS.Pa++;this.name=b;this.mode=c;this.ra=d;this.$=this.O=
this.N=Date.now()}get read(){return 365===(this.mode&365)}set read(a){a?this.mode|=365:this.mode&=-366}get write(){return 146===(this.mode&146)}set write(a){a?this.mode|=146:this.mode&=-147}get Zb(){return FS.isDir(this.mode)}get Yb(){return FS.isChrdev(this.mode)}},lookupPath(a,b={}){if(!a)throw new FS.h(44);b.wa??(b.wa=!0);"/"===a.charAt(0)||(a=FS.cwd()+"/"+a);var c=0;a:for(;40>c;c++){a=a.split("/").filter(k=>!!k);for(var d=FS.root,e="/",f=0;f<a.length;f++){var g=f===a.length-1;if(g&&b.parent)break;
if("."!==a[f])if(".."===a[f])if(e=Pe(e),FS.na(d)){a=e+"/"+a.slice(f+1).join("/");c--;continue a}else d=d.parent;else{e=Oe(e+"/"+a[f]);try{d=jf(d,a[f])}catch(k){if(44===k?.B&&g&&b.bc)return{path:e};throw k;}!d.T||g&&!b.wa||(d=d.T.root);if(FS.isLink(d.mode)&&(!g||b.follow)){if(!d.m.readlink)throw new FS.h(52);d=d.m.readlink(d);"/"===d.charAt(0)||(d=Pe(e)+"/"+d);a=d+"/"+a.slice(f+1).join("/");continue a}}}return{path:e,node:d}}throw new FS.h(32);},getPath(a){for(var b;;){if(FS.na(a))return a=a.mount.jb,
b?"/"!==a[a.length-1]?`${a}/${b}`:a+b:a;b=b?`${a.name}/${b}`:a.name;a=a.parent}},createNode(a,b,c,d){a=new FS.wb(a,b,c,d);rf(a);return a},na(a){return a===a.parent},isFile(a){return 32768===(a&61440)},isDir(a){return 16384===(a&61440)},isLink(a){return 40960===(a&61440)},isChrdev(a){return 8192===(a&61440)},isBlkdev(a){return 24576===(a&61440)},isSocket(a){return 49152===(a&49152)},yb:4096,cb:a=>FS.streams[a],Cb:{open(a){a.o=FS.Mb(a.node.ra).o;a.o.open?.(a)},llseek(){throw new FS.h(70);}},Ma:a=>a>>
8,Lc:a=>a&255,makedev:(a,b)=>a<<8|b,registerDevice(a,b){FS.Za[a]={o:b}},Mb:a=>FS.Za[a],syncfs(a,b){function c(k){FS.Ca--;return b(k)}function d(k){if(k){if(!d.Ib)return d.Ib=!0,c(k)}else++f>=e.length&&c(null)}"function"==typeof a&&(b=a,a=!1);FS.Ca++;1<FS.Ca&&t(`warning: ${FS.Ca} FS.syncfs operations in flight at once, probably just doing extra work`);var e=yf(FS.root.mount),f=0,g;for(g of e)g.type.syncfs?g.type.syncfs(g,a,d):d(null)},mount(a,b,c){var d="/"===c;if(d&&FS.root)throw new FS.h(10);if(!d&&
c){var e=FS.lookupPath(c,{wa:!1});c=e.path;e=e.node;if(e.T)throw new FS.h(10);if(!FS.isDir(e.mode))throw new FS.h(54);}b={type:a,cc:b,jb:c,oa:[]};a=a.mount(b);a.mount=b;b.root=a;d?FS.root=a:e&&(e.T=b,e.mount&&e.mount.oa.push(b));return a},unmount(a){a=FS.lookupPath(a,{wa:!1});if(!a.node.T)throw new FS.h(28);a=a.node;var b=a.T,c=yf(b);for([,e]of Object.entries(FS.da))for(;e;){var d=e.ka;c.includes(e.mount)&&kf(e);var e=d}a.T=null;a.mount.oa.splice(a.mount.oa.indexOf(b),1)},ia(a,b){return a.m.ia(a,
b)},ca(a,b,c){var d=FS.lookupPath(a,{parent:!0}).node;a=Qe(a);if(!a)throw new FS.h(28);if("."===a||".."===a)throw new FS.h(20);var e=sf(d,a);if(e)throw new FS.h(e);if(!d.m.ca)throw new FS.h(63);return d.m.ca(d,a,b,c)},rb(a){return zf(FS.lookupPath(a,{follow:!0}).node)},Pc(a){return zf(a.node)},create(a,b=438){return FS.ca(a,b&4095|32768,0)},mkdir(a,b=511){return FS.ca(a,b&1023|16384,0)},Mc(a,b){var c=a.split("/"),d="",e;for(e of c)if(e){if(d||"/"===a.charAt(0))d+="/";d+=e;try{FS.mkdir(d,b)}catch(f){if(20!=
f.B)throw f;}}},mkdev(a,b,c){"undefined"==typeof c&&(c=b,b=438);return FS.ca(a,b|8192,c)},symlink(a,b){if(!Ze(a))throw new FS.h(44);var c=FS.lookupPath(b,{parent:!0}).node;if(!c)throw new FS.h(44);b=Qe(b);var d=sf(c,b);if(d)throw new FS.h(d);if(!c.m.symlink)throw new FS.h(63);return c.m.symlink(c,b,a)},rename(a,b){var c=Pe(a),d=Pe(b),e=Qe(a),f=Qe(b);var g=FS.lookupPath(a,{parent:!0});var k=g.node;g=FS.lookupPath(b,{parent:!0});g=g.node;if(!k||!g)throw new FS.h(44);if(k.mount!==g.mount)throw new FS.h(75);
var l=jf(k,e);a=$e(a,d);if("."!==a.charAt(0))throw new FS.h(28);a=$e(b,c);if("."!==a.charAt(0))throw new FS.h(55);try{var m=jf(g,f)}catch(n){}if(l!==m){b=FS.isDir(l.mode);if(e=tf(k,e,b))throw new FS.h(e);if(e=m?tf(g,f,b):sf(g,f))throw new FS.h(e);if(!k.m.rename)throw new FS.h(63);if(l.T||m&&m.T)throw new FS.h(10);if(g!==k&&(e=pf(k,"w")))throw new FS.h(e);kf(l);try{k.m.rename(l,g,f),l.parent=g}catch(n){throw n;}finally{rf(l)}}},rmdir(a){var b=FS.lookupPath(a,{parent:!0}).node;a=Qe(a);var c=jf(b,a),
d=tf(b,a,!0);if(d)throw new FS.h(d);if(!b.m.rmdir)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.rmdir(b,a);kf(c)},sa(a){a=FS.lookupPath(a,{follow:!0}).node;return uf(a.m.sa,54)(a)},unlink(a){var b=FS.lookupPath(a,{parent:!0}).node;if(!b)throw new FS.h(44);a=Qe(a);var c=jf(b,a),d=tf(b,a,!1);if(d)throw new FS.h(d);if(!b.m.unlink)throw new FS.h(63);if(c.T)throw new FS.h(10);b.m.unlink(b,a);kf(c)},readlink(a){a=FS.lookupPath(a).node;if(!a)throw new FS.h(44);if(!a.m.readlink)throw new FS.h(28);return a.m.readlink(a)},
stat(a,b){a=FS.lookupPath(a,{follow:!b}).node;return uf(a.m.S,63)(a)},lstat(a){return FS.stat(a,!0)},chmod(a,b,c){a="string"==typeof a?FS.lookupPath(a,{follow:!c}).node:a;Af(null,a,b,c)},lchmod(a,b){FS.chmod(a,b,!0)},fchmod(a,b){a=S(a);Af(a,a.node,b,!1)},chown(a,b,c,d){a="string"==typeof a?FS.lookupPath(a,{follow:!d}).node:a;xf(null,a,{timestamp:Date.now(),$a:d})},lchown(a,b,c){FS.chown(a,b,c,!0)},fchown(a){a=S(a);xf(a,a.node,{timestamp:Date.now(),$a:!1})},truncate(a,b){if(0>b)throw new FS.h(28);
a="string"==typeof a?FS.lookupPath(a,{follow:!0}).node:a;Bf(null,a,b)},ftruncate(a,b){a=S(a);if(0>b||0===(a.flags&2097155))throw new FS.h(28);Bf(a,a.node,b)},utime(a,b,c){a=FS.lookupPath(a,{follow:!0}).node;uf(a.m.U,63)(a,{$:b,O:c})},open(a,b,c=438){if(""===a)throw new FS.h(44);if("string"==typeof b){var d={r:0,"r+":2,w:577,"w+":578,a:1089,"a+":1090}[b];if("undefined"==typeof d)throw Error(`Unknown file open mode: ${b}`);b=d}c=b&64?c&4095|32768:0;if("object"==typeof a)d=a;else{var e=a.endsWith("/");
var f=FS.lookupPath(a,{follow:!(b&131072),bc:!0});d=f.node;a=f.path}f=!1;if(b&64)if(d){if(b&128)throw new FS.h(20);}else{if(e)throw new FS.h(31);d=FS.ca(a,c|511,0);f=!0}if(!d)throw new FS.h(44);FS.isChrdev(d.mode)&&(b&=-513);if(b&65536&&!FS.isDir(d.mode))throw new FS.h(54);if(!f){e=d;a=b;if(e)if(FS.isLink(e.mode))e=32;else{var g=["r","w","rw"][a&3];a&512&&(g+="w");e=FS.isDir(e.mode)&&("r"!==g||a&576)?31:pf(e,g)}else e=44;if(e)throw new FS.h(e);}b&512&&!f&&FS.truncate(d,0);b&=-131713;b=vf({node:d,
path:FS.getPath(d),flags:b,seekable:!0,position:0,o:d.o,uc:[],error:!1});b.o.open&&b.o.open(b);f&&FS.chmod(d,c&511);return b},close(a){if(null===a.aa)throw new FS.h(8);a.Ga&&(a.Ga=null);try{a.o.close&&a.o.close(a)}catch(b){throw b;}finally{FS.streams[a.aa]=null}a.aa=null},llseek(a,b,c){if(null===a.aa)throw new FS.h(8);if(!a.seekable||!a.o.llseek)throw new FS.h(70);if(0!=c&&1!=c&&2!=c)throw new FS.h(28);a.position=a.o.llseek(a,b,c);a.uc=[];return a.position},read(a,b,c,d,e){if(0>d||0>e)throw new FS.h(28);
if(null===a.aa)throw new FS.h(8);if(1===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.read)throw new FS.h(28);var f="undefined"!=typeof e;if(!f)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.read(a,b,c,d,e);f||(a.position+=b);return b},write(a,b,c,d,e,f){if(0>d||0>e)throw new FS.h(28);if(null===a.aa)throw new FS.h(8);if(0===(a.flags&2097155))throw new FS.h(8);if(FS.isDir(a.node.mode))throw new FS.h(31);if(!a.o.write)throw new FS.h(28);a.seekable&&
a.flags&1024&&FS.llseek(a,0,2);var g="undefined"!=typeof e;if(!g)e=a.position;else if(!a.seekable)throw new FS.h(70);b=a.o.write(a,b,c,d,e,f);g||(a.position+=b);return b},ja(a,b,c,d,e){if(0!==(d&2)&&0===(e&2)&&2!==(a.flags&2097155))throw new FS.h(2);if(1===(a.flags&2097155))throw new FS.h(2);if(!a.o.ja)throw new FS.h(43);if(!b)throw new FS.h(28);return a.o.ja(a,b,c,d,e)},la(a,b,c,d,e){return a.o.la?a.o.la(a,b,c,d,e):0},Ja(a,b,c){if(!a.o.Ja)throw new FS.h(59);return a.o.Ja(a,b,c)},readFile(a,b={}){b.flags=
b.flags||0;b.encoding=b.encoding||"binary";"utf8"!==b.encoding&&"binary"!==b.encoding&&J(`Invalid encoding type "${b.encoding}"`);var c=FS.open(a,b.flags);a=FS.stat(a).size;var d=new Uint8Array(a);FS.read(c,d,0,a,0);"utf8"===b.encoding&&(d=qe(d));FS.close(c);return d},writeFile(a,b,c={}){c.flags=c.flags||577;a=FS.open(a,c.flags,c.mode);b=lf(b);FS.write(a,b,0,b.byteLength,void 0,c.Fc);FS.close(a)},cwd:()=>FS.Xa,chdir(a){a=FS.lookupPath(a,{follow:!0});if(null===a.node)throw new FS.h(44);if(!FS.isDir(a.node.mode))throw new FS.h(54);
var b=pf(a.node,"x");if(b)throw new FS.h(b);FS.Xa=a.path},init(a,b,c){FS.Ia=!0;a??=h.stdin;b??=h.stdout;c??=h.stderr;a?FS.createDevice("/dev","stdin",a):FS.symlink("/dev/tty","/dev/stdin");b?FS.createDevice("/dev","stdout",null,b):FS.symlink("/dev/tty","/dev/stdout");c?FS.createDevice("/dev","stderr",null,c):FS.symlink("/dev/tty1","/dev/stderr");FS.open("/dev/stdin",0);FS.open("/dev/stdout",1);FS.open("/dev/stderr",1)},Ic(a,b){a=FS.analyzePath(a,b);return a.ab?a.object:null},analyzePath(a,b){try{var c=
FS.lookupPath(a,{follow:!b});a=c.path}catch(e){}var d={na:!1,ab:!1,error:0,name:null,path:null,object:null,dc:!1,hc:null,fc:null};try{c=FS.lookupPath(a,{parent:!0}),d.dc=!0,d.hc=c.path,d.fc=c.node,d.name=Qe(a),c=FS.lookupPath(a,{follow:!b}),d.ab=!0,d.path=c.path,d.object=c.node,d.name=c.node.name,d.na="/"===c.path}catch(e){d.error=e.B}return d},createPath(a,b){a="string"==typeof a?a:FS.getPath(a);for(b=b.split("/").reverse();b.length;){var c=b.pop();if(c){var d=Oe(a+"/"+c);try{FS.mkdir(d)}catch(e){if(20!=
e.B)throw e;}a=d}}return d},createDataFile(a,b,c,d,e,f){var g=b;a&&(a="string"==typeof a?a:FS.getPath(a),g=b?Oe(a+"/"+b):a);a=mf(d,e);g=FS.create(g,a);c&&(c=lf(c),FS.chmod(g,a|146),b=FS.open(g,577),FS.write(b,c,0,c.length,0,f),FS.close(b),FS.chmod(g,a))},createDevice(a,b,c,d){a=Re("string"==typeof a?a:FS.getPath(a),b);b=mf(!!c,!!d);var e;(e=FS.createDevice).Ma??(e.Ma=64);e=FS.makedev(FS.createDevice.Ma++,0);FS.registerDevice(e,{open(f){f.seekable=!1},close(){d?.buffer?.length&&d(10)},read(f,g,k,l){for(var m=
0,n=0;n<l;n++){try{var r=c()}catch(u){throw new FS.h(29);}if(void 0===r&&0===m)throw new FS.h(6);if(null===r||void 0===r)break;m++;g[k+n]=r}m&&(f.node.$=Date.now());return m},write(f,g,k,l){for(var m=0;m<l;m++)try{d(g[k+m])}catch(n){throw new FS.h(29);}l&&(f.node.O=f.node.N=Date.now());return m}});return FS.mkdev(a,b,e)},createLazyFile(a,b,c,d,e){function f(n,r,u,q,v){n=n.node.u;if(v>=n.length)return 0;q=Math.min(n.length-v,q);if(n.slice)for(var x=0;x<q;x++)r[u+x]=n[v+x];else for(x=0;x<q;x++)r[u+
x]=n.get(v+x);return q}class g{Ha=!1;P=[];ma=void 0;ib=0;hb=0;get(n){if(!(n>this.length-1||0>n)){var r=n%this.qb;return this.ma(n/this.qb|0)[r]}}tc(n){this.ma=n}kb(){var n=new XMLHttpRequest;n.open("HEAD",c,!1);n.send(null);200<=n.status&&300>n.status||304===n.status||J("Couldn't load "+c+". Status: "+n.status);var r=Number(n.getResponseHeader("Content-length")),u,q=(u=n.getResponseHeader("Accept-Ranges"))&&"bytes"===u;n=(u=n.getResponseHeader("Content-Encoding"))&&"gzip"===u;var v=1048576;q||(v=
r);var x=this;x.tc(C=>{var B=C*v,E=(C+1)*v-1;E=Math.min(E,r-1);if("undefined"==typeof x.P[C]){var K=x.P;B>E&&J("invalid range ("+B+", "+E+") or no bytes requested!");E>r-1&&J("only "+r+" bytes available! programmer error!");var D=new XMLHttpRequest;D.open("GET",c,!1);r!==v&&D.setRequestHeader("Range","bytes="+B+"-"+E);D.responseType="arraybuffer";D.overrideMimeType&&D.overrideMimeType("text/plain; charset=x-user-defined");D.send(null);200<=D.status&&300>D.status||304===D.status||J("Couldn't load "+
c+". Status: "+D.status);B=void 0!==D.response?new Uint8Array(D.response||[]):bf(D.responseText||"");K[C]=B}"undefined"==typeof x.P[C]&&J("doXHR failed!");return x.P[C]});if(n||!r)v=r=1,v=r=this.ma(0).length,ja("LazyFiles on gzip forces download of the whole file when length is accessed");this.ib=r;this.hb=v;this.Ha=!0}get length(){this.Ha||this.kb();return this.ib}get qb(){this.Ha||this.kb();return this.hb}}if(globalThis.XMLHttpRequest){ba||J("Cannot do synchronous binary XHRs outside webworkers in modern browsers. Use --embed-file or --preload-file in emcc");
var k=new g;var l=void 0}else l=c,k=void 0;var m=Cf(a,b,d,e);k?m.u=k:l&&(m.u=null,m.url=l);Object.defineProperties(m,{L:{get:function(){return this.u.length}}});a={};for(const [n,r]of Object.entries(m.o))a[n]=(...u)=>{Df(m);return r(...u)};a.read=(n,r,u,q,v)=>{Df(m);return f(n,r,u,q,v)};a.ja=(n,r,u)=>{Df(m);var q=hf(r);if(!q)throw new FS.h(48);f(n,(w(),y),q,r,u);return{A:q,fa:!0}};m.o=a;return m}},Je=(a,b)=>{if(Ia){if("/"===a.charAt(0))try{return FS.lookupPath(a),a}catch(d){return}var c=(b?.ic||[]).map(d=>
{var e=b?.ec;return d.startsWith("$ORIGIN")?d.replace("$ORIGIN",Pe(e)):d});return Se(()=>{var d=vd(512),e=We(c.join(":")),f=We(a);return(d=ld(d,e,f,512))?Q(d):void 0})}};
function Ke(a,b={global:!0,pa:!0},c,d){function e(){var l=ua[a];if(l)return b.I?Promise.resolve(l):l;if(d){l=(w(),H)[d+28>>2];var m=(w(),H)[d+32>>2];if(l&&m)return l=(w(),y).slice(l,l+m),b.I?Promise.resolve(l):l}if(l=Je(a,b.Sa))return l=FS.readFile(l,{encoding:"binary"}),b.I?Promise.resolve(l):l;l=fa(a);if(b.I)return Me(l);if(!ia)throw Error(`${l}: file not found, and synchronous loading of external files is not available`);return ia(l)}function f(){var l=ge[a];return l?b.I?Promise.resolve(l):l:b.I?
e().then(m=>Le(m,b,a,c,d)):Le(e(),b,a,c,d)}function g(l){k.global?Wc(l):c&&Object.assign(c,l);k.exports=l}var k=re[a];if(k)return b.global?k.global||(k.global=!0,Wc(k.exports)):c&&Object.assign(c,k.exports),b.pa&&Infinity!==k.Aa&&(k.Aa=Infinity),k.Aa++,d&&(se[d]=k),b.I?Promise.resolve(!0):!0;k=Cd(a,d,"loading");k.Aa=b.pa?Infinity:1;k.global=b.global;if(b.I)return f().then(l=>{g(l);return!0});g(f());return!0}
var Ie=()=>{var a,b;for([a,b]of Object.entries(me))if(-1==b.value){var c=Ge(a).Ta;if(c||b.required)if("function"==typeof c)b.value=Ce(c,c.g);else if("number"==typeof c)b.value=c;else if("number"==typeof c.value)b.value=c;else throw Error(`bad export type for '${a}': ${typeof c} (${c})`);else b.value=0}},Dd=async()=>{if(ka.length){Sd("loadDylibs");for(var a of ka)await Ke(a,{I:!0,global:!0,pa:!0,zb:!0});Ie();Rd("loadDylibs")}else Ie()},ce=!1,Yc=(a,b,c)=>{function d(){var e=a();if(e){var f={};c.sb.forEach(g=>
f[g]=b[g]);Bd(De(f,e),!0)}}Xd.push(d);Ia&&d()},qa,Ya=(a,b,c,d)=>J(`Assertion failed: ${Q(a)}, at: `+[b?Q(b):"unknown filename",c,d?Q(d):"unknown function"]);Ya.g="vppip";var Za=(a,b)=>N.get(a)(b);Za.g="vpi";function $a(...a){return L.__lsan_ignore_object(...a)}$a.Ba=!0;function Ef(a,b,c,d){return p?P(2,1,a,b,c,d):bb(a,b,c,d)}
var bb=(a,b,c,d)=>{if(!globalThis.SharedArrayBuffer)return 6;var e=[];if(p&&0===e.length)return Ef(a,b,c,d);a={rc:c,X:a,Ea:d,tb:e};return p?(a.V="spawnThread",postMessage(a,e),0):Vd(a)};bb.g="ipppp";var Ff=18;function Gf(a,b,c){if("/"===b.charAt(0))return b;a=-100===a?FS.cwd():S(a).path;if(0==b.length){if(!c)throw new FS.h(44);return a}return a+"/"+b}
function Hf(a,b){(w(),H)[a>>2]=b.Eb;(w(),H)[a+4>>2]=b.mode;(w(),H)[a+8>>2]=b.ac;(w(),H)[a+12>>2]=b.uid;(w(),H)[a+16>>2]=b.Qb;(w(),H)[a+20>>2]=b.ra;(w(),I)[a+24>>3]=BigInt(b.size);(w(),G)[a+32>>2]=4096;(w(),G)[a+36>>2]=b.Va;var c=b.$.getTime(),d=b.O.getTime(),e=b.N.getTime();(w(),I)[a+40>>3]=BigInt(Math.floor(c/1E3));(w(),H)[a+48>>2]=c%1E3*1E6;(w(),I)[a+56>>3]=BigInt(Math.floor(d/1E3));(w(),H)[a+64>>2]=d%1E3*1E6;(w(),I)[a+72>>3]=BigInt(Math.floor(e/1E3));(w(),H)[a+80>>2]=e%1E3*1E6;(w(),I)[a+88>>3]=
BigInt(b.Ub);return 0}var If=void 0;function cb(a){if(p)return P(3,1,a);try{var b=S(a);return wf(b).aa}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}cb.g="ii";function db(a,b,c,d){if(p)return P(4,1,a,b,c,d);try{b=Q(b);b=Gf(a,b);if(c&-8)return-28;var e=FS.lookupPath(b,{follow:!0}).node;if(!e)return-44;a="";c&4&&(a+="r");c&2&&(a+="w");c&1&&(a+="x");return a&&pf(e,a)?-2:0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}db.g="iipii";
var Jf=()=>{var a=(w(),G)[+If>>2];If+=4;return a};function eb(a,b,c){if(p)return P(5,1,a,b,c);If=c;try{var d=S(a);switch(b){case 0:var e=Jf();if(0>e)break;for(;FS.streams[e];)e++;return wf(d,e).aa;case 1:case 2:return 0;case 3:return d.flags;case 4:return e=Jf(),d.flags=d.flags&-289793|e&289792,0;case 12:return e=Jf(),(w(),z)[e+0>>1]=2,0;case 13:case 14:return 0}return-28}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}eb.g="iiip";
function fb(a,b){if(p)return P(6,1,a,b);try{var c=S(a),d=c.node,e=c.o.S;a=e?c:d;e??=d.m.S;uf(e,63);var f=e(a);return Hf(b,f)}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}fb.g="iip";function gb(a,b){if(p)return P(7,1,a,b);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return-22;FS.ftruncate(a,b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}gb.g="iij";
function hb(a,b){if(p)return P(8,1,a,b);try{if(0===b)return-28;var c=FS.cwd(),d=Te(c)+1;if(b<d)return-68;Ve(c,a,b);return d}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return-e.B}}hb.g="ipp";
function ib(a,b,c){if(p)return P(9,1,a,b,c);If=c;try{var d=S(a);switch(b){case 21509:return d.C?0:-59;case 21505:if(!d.C)return-59;if(d.C.ea.Vb){a=[3,28,127,21,4,0,1,0,17,19,26,0,18,15,23,22,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0];var e=Jf();(w(),G)[e>>2]=25856;(w(),G)[e+4>>2]=5;(w(),G)[e+8>>2]=191;(w(),G)[e+12>>2]=35387;for(var f=0;32>f;f++)(w(),y)[e+f+17]=a[f]||0}return 0;case 21510:case 21511:case 21512:return d.C?0:-59;case 21506:case 21507:case 21508:if(!d.C)return-59;if(d.C.ea.Wb)for(e=Jf(),w(),w(),
w(),w(),a=[],f=0;32>f;f++)a.push((w(),y)[e+f+17]);return 0;case 21519:if(!d.C)return-59;e=Jf();return(w(),G)[e>>2]=0;case 21520:return d.C?-28:-59;case 21537:case 21531:return e=Jf(),FS.Ja(d,b,e);case 21523:if(!d.C)return-59;d.C.ea.Xb&&(f=[24,80],e=Jf(),(w(),z)[e>>1]=f[0],(w(),z)[e+2>>1]=f[1]);return 0;case 21524:return d.C?0:-59;case 21515:return d.C?0:-59;default:return-28}}catch(g){if("undefined"==typeof FS||"ErrnoError"!==g.name)throw g;return-g.B}}ib.g="iiip";
function jb(a,b){if(p)return P(10,1,a,b);try{return a=Q(a),Hf(b,FS.lstat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}jb.g="ipp";function kb(a,b,c,d){if(p)return P(11,1,a,b,c,d);try{b=Q(b);var e=d&256;b=Gf(a,b,d&4096);return Hf(c,e?FS.lstat(b):FS.stat(b))}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}kb.g="iippi";
function lb(a,b,c,d){if(p)return P(12,1,a,b,c,d);If=d;try{b=Q(b);b=Gf(a,b);var e=d?Jf():0;c&64&&(e&=~Ff);return FS.open(b,c,e).aa}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return-f.B}}lb.g="iipip";
function mb(a,b,c){if(p)return P(13,2,a,b,c);try{const x=be;var d,e=new Promise(E=>{d=E}),f=[],g=!1;function C(E){g||(g=!0,f.forEach(K=>K()),d(E))}function B(E,K){return D=>{if(!g){var na=(w(),z)[K+4>>1];D&=na|24;(w(),z)[K+6>>1]=D;C(1)}}}if(x&&0<c){var k=setTimeout(()=>{C(0)},c);f.push(()=>clearTimeout(k))}for(var l=0,m=0;m<b;m++){var n=a+8*m,r=(w(),G)[n>>2],u=(w(),z)[n+4>>1],q=32,v=FS.cb(r);v&&(v.o.lb?q=x&&c?v.o.lb(v,c,B(v,n)):v.o.lb(v,-1):q=5);(q&=u|24)&&l++;(w(),z)[n+6>>1]=q}return x?(!l&&c||C(l),
e):l}catch(x){if("undefined"==typeof FS||"ErrnoError"!==x.name)throw x;return-x.B}}mb.g="ipii";function nb(a){if(p)return P(14,1,a);try{return a=Q(a),FS.rmdir(a),0}catch(b){if("undefined"==typeof FS||"ErrnoError"!==b.name)throw b;return-b.B}}nb.g="ip";function ob(a,b){if(p)return P(15,1,a,b);try{return a=Q(a),Hf(b,FS.stat(a))}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return-c.B}}ob.g="ipp";
function pb(a,b,c){if(p)return P(16,1,a,b,c);try{b=Q(b);b=Gf(a,b);if(c)if(512===c)FS.rmdir(b);else return-28;else FS.unlink(b);return 0}catch(d){if("undefined"==typeof FS||"ErrnoError"!==d.name)throw d;return-d.B}}pb.g="iipi";var qb=a=>{a=new WebAssembly.Exception(zd,[a],{traceStack:!0});var b=a.getArg(zd,0);var c=xd(b);b=wd();var d=vd(4),e=vd(4);yd(c,d,e);c=(w(),H)[d>>2];e=(w(),H)[e>>2];d=Q(c);M(c);if(e){var f=Q(e);M(e)}ud(b);a.message=[d,f];throw a;},rb=()=>J("");rb.g="v";
var Kf=a=>{var b=wd();a=We(a);fd(a,0);ud(b)},Lf=(a,b)=>{var c=Q(a+36),d=(w(),G)[a+4>>2];c=Oe(c);var e=!!(d&256),f=e?null:{};d={global:e,pa:!!(d&4096),I:b.I};if(b.I)return Ke(c,d,f,a);try{return Ke(c,d,f,a)}catch(g){return Kf(`could not load dynamic lib: ${c}\n${g}`),0}},sb=a=>Lf(a,{I:!1});sb.g="pp";var tb=(a,b)=>{a=se[a].exports;b=Object.keys(a)[b];b=a[b];return Ce(b,b.g)};tb.g="ppi";
var ub=(a,b,c)=>{b=Q(b);var d=se[a];a=Object.keys(d.exports).indexOf(b);if(-1==a||d.exports[b].Ba)return Kf(`Tried to lookup unknown symbol "${b}" in dynamic lib: ${d.name}`),0;b=d.exports[b];"function"==typeof b&&((d=xe(b))?b=d:(b=Ce(b,b.g),(w(),H)[c>>2]=a));return b};ub.g="pppp";var Mf={},Nf=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function Of(a){return this.v((w(),H)[a>>2])}
var Pf={},Qf={},Rf={},Sf=class extends Error{constructor(a){super(a);this.name="InternalError"}},U=(a,b,c)=>{function d(k){k=c(k);if(k.length!==a.length)throw new Sf("Mismatched type converter count");for(var l=0;l<a.length;++l)T(a[l],k[l])}a.forEach(k=>Rf[k]=b);var e=Array(b.length),f=[],g=0;for(let [k,l]of b.entries())Qf.hasOwnProperty(l)?e[k]=Qf[l]:(f.push(l),Pf.hasOwnProperty(l)||(Pf[l]=[]),Pf[l].push(()=>{e[k]=Qf[l];++g;g===f.length&&d(e)}));0===f.length&&d(e)},vb=a=>{var b=Mf[a];delete Mf[a];
var c=b.Ra,d=b.Y,e=b.bb,f=e.map(g=>g.Pb).concat(e.map(g=>g.nc));U([a],f,g=>{var k={},l,m;for([l,m]of e.entries()){const n=g[l],r=m.ma,u=m.Ob,q=g[l+e.length],v=m.mc,x=m.oc;k[m.Jb]={read:C=>n.v(r(u,C)),write:(C,B)=>{var E=[];v(x,C,q.F(E,B));Nf(E)},optional:n.optional}}return[{name:b.name,v:n=>{var r={},u;for(u in k)r[u]=k[u].read(n);d(n);return r},F:(n,r)=>{for(var u in k)if(!(u in r||k[u].optional))throw new TypeError(`Missing field: "${u}"`);var q=c();for(u in k)k[u].write(q,r[u]);null!==n&&n.push(d,
q);return q},K:Of,H:d}]})};vb.g="vp";var V=a=>{for(var b="";;){var c=(w(),A)[a++];if(!c)return b;b+=String.fromCharCode(c)}},W=class extends Error{constructor(a){super(a);this.name="BindingError"}},Tf=a=>{throw new W(a);};
function Uf(a,b,c={}){var d=b.name;if(!a)throw new W(`type "${d}" must have a positive integer typeid pointer`);if(Qf.hasOwnProperty(a)){if(c.Tb)return;throw new W(`Cannot register type '${d}' twice`);}Qf[a]=b;delete Rf[a];Pf.hasOwnProperty(a)&&(b=Pf[a],delete Pf[a],b.forEach(e=>e()))}function T(a,b,c={}){return Uf(a,b,c)}
var Vf=(a,b)=>{switch(b){case 4:return w(),Ka;case 8:return w(),La;default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Wf=(a,b,c)=>{switch(b){case 1:return c?(w(),y):(w(),A);case 2:return c?(w(),z):(w(),F);case 4:return c?(w(),G):(w(),H);case 8:return c?(w(),I):(w(),Ma);default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},wb=(a,b,c,d,e)=>{b=V(b);var f=d?Vf(b,c):Wf(b,c,e),g=Math.log2(c);T(a,{name:b,v:k=>{var l=(w(),H)[k>>2],m=k+Math.max(4,c)>>g;l=Array.from(f.subarray(m,
m+l));M(k);return l},F:(k,l)=>{"number"==typeof l&&(l=[l]);if(!Array.isArray(l))throw new W(`Cannot pass non-array to C++ vector type ${b}`);l=Array.prototype.concat.apply([],l);var m=l.length,n=Math.max(4,c),r=$c(n+m*c);n=r+n>>g;(w(),H)[r>>2]=m;f.set(l,n);null!==k&&k.push(M,r);return r},K:Of,H(k){M(k)}})};wb.g="vpppii";
var Xf=(a,b,c)=>{switch(b){case 1:return c?d=>(w(),y)[d]:d=>(w(),A)[d];case 2:return c?d=>(w(),z)[d>>1]:d=>(w(),F)[d>>1];case 4:return c?d=>(w(),G)[d>>2]:d=>(w(),H)[d>>2];case 8:return c?d=>(w(),I)[d>>3]:d=>(w(),Ma)[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},xb=(a,b,c,d,e)=>{b=V(b);d=0n===d;let f=g=>g;if(d){const g=8*c;f=k=>BigInt.asUintN(g,k);e=f(e)}T(a,{name:b,v:f,F:(g,k)=>{"number"==typeof k&&(k=BigInt(k));return k},K:Xf(b,c,!d),H:null})};xb.g="vpppjj";
var Ab=(a,b,c,d)=>{b=V(b);T(a,{name:b,v:function(e){return!!e},F:function(e,f){return f?c:d},K:function(e){return this.v((w(),A)[e])},H:null})};Ab.g="vppii";
var Yf=a=>{throw new W(a.l.D.s.name+" instance already deleted");},Zf=!1,$f=!1,ag=()=>{},bg=a=>{if(Zf)return bg=b=>b.deleteLater(),bg(a);if(!globalThis.FinalizationRegistry)return bg=b=>b,a;$f=new FinalizationRegistry(b=>{b=b.l;--b.count.value;0===b.count.value&&(b.J?b.R.Y(b.J):b.D.s.Y(b.A))});bg=b=>{var c=b.l;c.J&&$f.register(b,{l:c},b);return b};ag=b=>{$f.unregister(b)};return bg(a)},cg=[],dg=()=>{for(;cg.length;){var a=cg.pop();a.l.ha=!1;a["delete"]()}},eg;function fg(){}
var gg={},hg=(a,b,c)=>{if(void 0===a[b].G){var d=a[b];a[b]=function(...e){if(!a[b].G.hasOwnProperty(e.length))throw new W(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].G})!`);return a[b].G[e.length].apply(this,e)};a[b].G=[];a[b].G[d.Z]=d}},ig=(a,b,c)=>{if(h.hasOwnProperty(a)){if(void 0===c||void 0!==h[a].G&&void 0!==h[a].G[c])throw new W(`Cannot register public name '${a}' twice`);hg(h,a,a);if(h[a].G.hasOwnProperty(c))throw new W(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
h[a].G[c]=b}else h[a]=b,h[a].Z=c},jg=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function kg(a,b,c,d,e,f,g,k){this.name=a;this.constructor=b;this.ba=c;this.Y=d;this.M=e;this.Lb=f;this.ua=g;this.Fb=k;this.kc=[]}
var lg=(a,b,c)=>{for(;b!==c;){if(!b.ua)throw new W(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.ua(a);b=b.M}return a},mg=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function ng(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${mg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);return lg(b.l.A,b.l.D.s,this.s)}
function og(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);if(this.za){var c=this.Ra();null!==a&&a.push(this.Y,c);return c}return 0}if(!b||!b.l)throw new W(`Cannot pass "${mg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.ya&&b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);c=lg(b.l.A,b.l.D.s,this.s);if(this.za){if(void 0===b.l.J)throw new W("Passing raw pointer to smart pointer is illegal");
switch(this.qc){case 0:if(b.l.R===this)c=b.l.J;else throw new W(`Cannot convert argument of type ${b.l.R?b.l.R.name:b.l.D.name} to parameter type ${this.name}`);break;case 1:c=b.l.J;break;case 2:if(b.l.R===this)c=b.l.J;else{var d=b.clone();c=this.lc(c,pg(()=>d["delete"]()));null!==a&&a.push(this.Y,c)}break;default:throw new W("Unsupported sharing policy");}}return c}
function qg(a,b){if(null===b){if(this.Ka)throw new W(`null is not a valid ${this.name}`);return 0}if(!b.l)throw new W(`Cannot pass "${mg(b)}" as a ${this.name}`);if(!b.l.A)throw new W(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.l.D.ya)throw new W(`Cannot convert argument of type ${b.l.D.name} to parameter type ${this.name}`);return lg(b.l.A,b.l.D.s,this.s)}
var rg=(a,b,c)=>{if(b===c)return a;if(void 0===c.M)return null;a=rg(a,b,c.M);return null===a?null:c.Fb(a)},sg={},tg=(a,b)=>{if(void 0===b)throw new W("ptr should not be undefined");for(;a.M;)b=a.ua(b),a=a.M;return sg[b]},ug=(a,b)=>{if(!b.D||!b.A)throw new Sf("makeClassHandle requires ptr and ptrType");if(!!b.R!==!!b.J)throw new Sf("Both smartPtrType and smartPtr must be specified");b.count={value:1};return bg(Object.create(a,{l:{value:b,writable:!0}}))};
function vg(a,b,c,d,e,f,g,k,l,m,n){this.name=a;this.s=b;this.Ka=c;this.ya=d;this.za=e;this.jc=f;this.qc=g;this.nb=k;this.Ra=l;this.lc=m;this.Y=n;e||void 0!==b.M?this.F=og:(this.F=d?ng:qg,this.H=null)}var wg=(a,b,c)=>{if(!h.hasOwnProperty(a))throw new Sf("Replacing nonexistent public symbol");void 0!==h[a].G&&void 0!==c?h[a].G[c]=b:(h[a]=b,h[a].Z=c)},X=(a,b)=>{a=V(a);var c=N.get(b);if("function"!=typeof c)throw new W(`unknown function pointer with signature ${a}: ${b}`);return c};
class xg extends Error{}
var yg=a=>{a=cd(a);var b=V(a);M(a);return b},zg=(a,b)=>{function c(f){e[f]||Qf[f]||(Rf[f]?Rf[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new xg(`${a}: `+d.map(yg).join([", "]));},Bb=(a,b,c,d,e,f,g,k,l,m,n,r,u)=>{n=V(n);f=X(e,f);k&&=X(g,k);m&&=X(l,m);u=X(r,u);var q=jg(n);ig(q,function(){zg(`Cannot construct ${n} due to unbound types`,[d])});U([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var x=v.s;var C=x.ba}else C=fg.prototype;v=Fe(n,function(...D){if(Object.getPrototypeOf(this)!==B)throw new W(`Use 'new' to construct ${n}`);
if(void 0===E.ga)throw new W(`${n} has no accessible constructor`);var na=E.ga[D.length];if(void 0===na)throw new W(`Tried to invoke ctor of ${n} with invalid number of parameters (${D.length}) - expected (${Object.keys(E.ga).toString()}) parameters instead!`);return na.apply(this,D)});var B=Object.create(C,{constructor:{value:v}});v.prototype=B;var E=new kg(n,v,B,u,x,f,k,m);if(E.M){var K;(K=E.M).va??(K.va=[]);E.M.va.push(E)}x=new vg(n,E,!0,!1,!1);K=new vg(n+"*",E,!1,!1,!1);C=new vg(n+" const*",E,
!1,!0,!1);gg[a]={pointerType:K,Db:C};wg(q,v);return[x,K,C]})};Bb.g="vppppppppppppp";function Ag(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].H)return!0;return!1}
function Bg(a,b,c,d,e,f){var g=b.length;if(2>g)throw new W("argTypes array size mismatch! Must at least get return value and 'this' types!");var k=null!==b[1]&&null!==c,l=Ag(b);c=!b[0].gb;var m=b[0],n=b[1];d=[a,Tf,d,e,Nf,m.v.bind(m),n?.F.bind(n)];for(e=2;e<g;++e)m=b[e],d.push(m.F.bind(m));if(!l)for(e=k?1:2;e<b.length;++e)null!==b[e].H&&d.push(b[e].H);l=Ag(b);e=b.length-2;n=[];m=["fn"];k&&m.push("thisWired");for(g=0;g<e;++g)n.push(`arg${g}`),m.push(`arg${g}Wired`);n=n.join(",");m=m.join(",");n=`return function (${n}) {\n`;
l&&(n+="var destructors = [];\n");var r=l?"destructors":"null",u="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");k&&(n+=`var thisWired = toClassParamWire(${r}, this);\n`);for(g=0;g<e;++g){var q=`toArg${g}Wire`;n+=`var arg${g}Wired = ${q}(${r}, arg${g});\n`;u.push(q)}n+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(l)n+="runDestructors(destructors);\n";else for(g=k?1:2;g<b.length;++g)f=1===g?"thisWired":"arg"+(g-2)+"Wired",null!==b[g].H&&(n+=`${f}_dtor(${f});\n`,
u.push(`${f}_dtor`));c&&(n+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(u,n+"}\n"))(...d);return Fe(a,b)}
var Cg=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push((w(),H)[b+4*d>>2]);return c},Gg=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},Cb=(a,b,c,d,e,f,g,k)=>{var l=Cg(c,d);b=V(b);b=Gg(b);f=X(e,f);U([],[a],m=>{function n(){zg(`Cannot call ${r} due to unbound types`,l)}m=m[0];var r=`${m.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);var u=m.s.constructor;void 0===u[b]?(n.Z=c-1,u[b]=n):(hg(u,b,r),u[b].G[c-1]=n);U([],l,q=>{q=Bg(r,[q[0],null].concat(q.slice(1)),null,f,g,k);void 0===
u[b].G?(q.Z=c-1,u[b]=q):u[b].G[c-1]=q;if(m.s.va)for(const v of m.s.va)v.constructor.hasOwnProperty(b)||(v.constructor[b]=q);return[]});return[]})};Cb.g="vppippppii";
var Db=(a,b,c,d,e,f)=>{var g=Cg(b,c);e=X(d,e);U([],[a],k=>{k=k[0];var l=`constructor ${k.name}`;void 0===k.s.ga&&(k.s.ga=[]);if(void 0!==k.s.ga[b-1])throw new W(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${k.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);k.s.ga[b-1]=()=>{zg(`Cannot construct ${k.name} due to unbound types`,g)};U([],g,m=>{m.splice(1,0,null);k.s.ga[b-1]=Bg(l,m,null,e,f);return[]});
return[]})};Db.g="vpipppp";var Eb=(a,b,c,d,e,f,g,k,l)=>{var m=Cg(c,d);b=V(b);b=Gg(b);f=X(e,f);U([],[a],n=>{function r(){zg(`Cannot call ${u} due to unbound types`,m)}n=n[0];var u=`${n.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);k&&n.s.kc.push(b);var q=n.s.ba,v=q[b];void 0===v||void 0===v.G&&v.className!==n.name&&v.Z===c-2?(r.Z=c-2,r.className=n.name,q[b]=r):(hg(q,b,u),q[b].G[c-2]=r);U([],m,x=>{x=Bg(u,x,n,f,g,l);void 0===q[b].G?(x.Z=c-2,q[b]=x):q[b].G[c-2]=x;return[]});return[]})};
Eb.g="vppippppiii";
var Hg=(a,b,c)=>{if(!(a instanceof Object))throw new W(`${c} with invalid "this": ${a}`);if(!(a instanceof b.s.constructor))throw new W(`${c} incompatible with "this" of type ${a.constructor.name}`);if(!a.l.A)throw new W(`cannot call emscripten binding method ${c} on deleted object`);return lg(a.l.A,a.l.D.s,b.s)},Fb=(a,b,c,d,e,f,g,k,l,m)=>{b=V(b);e=X(d,e);U([],[a],n=>{n=n[0];var r=`${n.name}.${b}`,u={get(){zg(`Cannot access ${r} due to unbound types`,[c,g])},enumerable:!0,configurable:!0};u.set=l?
()=>zg(`Cannot access ${r} due to unbound types`,[c,g]):()=>{throw new W(r+" is a read-only property");};Object.defineProperty(n.s.ba,b,u);U([],l?[c,g]:[c],q=>{var v=q[0],x={get(){var B=Hg(this,n,r+" getter");return v.v(e(f,B))},enumerable:!0};if(l){l=X(k,l);var C=q[1];x.set=function(B){var E=Hg(this,n,r+" setter"),K=[];l(m,E,C.F(K,B));Nf(K)}}Object.defineProperty(n.s.ba,b,x);return[]});return[]})};Fb.g="vpppppppppp";
var Ig=[],Jg=[0,1,,1,null,1,!0,1,!1,1],Kg=[],fc=a=>{if(9<a&&0===--Jg[a+1]){var b=Jg[a];Jg[a]=void 0;var c=Kg[a];c&&(Kg[a]=void 0,c(b));Ig.push(a)}};fc.g="vp";var Y=a=>{if(!a)throw new W(`Cannot use deleted val. handle = ${a}`);return Jg[a]},pg=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=Ig.pop()||Jg.length;Jg[b]=a;Jg[b+1]=1;return b}},Lg={name:"emscripten::val",v:a=>{var b=Y(a);fc(a);return b},F:(a,b)=>pg(b),K:Of,H:null},Gb=a=>T(a,Lg);
Gb.g="vp";
var Mg=(a,b,c)=>{switch(b){case 1:return c?function(d){return this.v((w(),y)[d])}:function(d){return this.v((w(),A)[d])};case 2:return c?function(d){return this.v((w(),z)[d>>1])}:function(d){return this.v((w(),F)[d>>1])};case 4:return c?function(d){return this.v((w(),G)[d>>2])}:function(d){return this.v((w(),H)[d>>2])};default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Hb=(a,b,c,d,e)=>{b=V(b);e=0===e?"object":1===e?"number":"string";switch(e){case "object":function g(){}g.values={};
T(a,{name:b,constructor:g,valueType:e,v:function(k){return this.constructor.values[k]},F:(k,l)=>l.value,K:Mg(b,c,d),H:null});ig(b,g);break;case "number":var f={};T(a,{name:b,La:f,valueType:e,v:k=>k,F:(k,l)=>l,K:Mg(b,c,d),H:null});ig(b,f);delete h[b].Z;break;case "string":f={},T(a,{name:b,ub:{},ob:{},La:f,valueType:e,v:function(k){return this.ob[k]},F:function(k,l){return this.ub[l]},K:Mg(b,c,d),H:null}),ig(b,f),delete h[b].Z}};Hb.g="vpppii";
var Ng=(a,b)=>{var c=Qf[a];if(void 0===c)throw a=`${b} has unknown type ${yg(a)}`,new W(a);return c},Ib=(a,b,c)=>{var d=Ng(a,"enum");b=V(b);switch(d.valueType){case "object":a=d.constructor;d=Object.create(d.constructor.prototype,{value:{value:c},constructor:{value:Fe(`${d.name}_${b}`,function(){})}});a.values[c]=d;a[b]=d;break;case "number":d.La[b]=c;break;case "string":d.ub[b]=c,d.ob[c]=b,d.La[b]=b}};Ib.g="vppi";
var Og=(a,b)=>{switch(b){case 4:return function(c){return this.v((w(),Ka)[c>>2])};case 8:return function(c){return this.v((w(),La)[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},Jb=(a,b,c)=>{b=V(b);T(a,{name:b,v:d=>d,F:(d,e)=>e,K:Og(b,c),H:null})};Jb.g="vppp";var Kb=(a,b,c,d,e,f,g)=>{var k=Cg(b,c);a=V(a);a=Gg(a);e=X(d,e);ig(a,function(){zg(`Cannot call ${a} due to unbound types`,k)},b-1);U([],k,l=>{wg(a,Bg(a,[l[0],null].concat(l.slice(1)),null,e,f,g),b-1);return[]})};
Kb.g="vpippppii";var Lb=(a,b,c,d,e)=>{b=V(b);let f=k=>k;if(0===d){var g=32-8*c;f=k=>k<<g>>>g;e=f(e)}T(a,{name:b,v:f,F:(k,l)=>l,K:Xf(b,c,0!==d),H:null})};Lb.g="vpppii";var Pg=(a,b,c)=>{const d=(e,f)=>{let g=0;return{next(){if(g>=e)return{done:!0};const k=g;g++;return{value:f(k),done:!1}},[Symbol.iterator](){return this}}};a[Symbol.iterator]||(a[Symbol.iterator]=function(){const e=this[b]();return d(e,f=>this[c](f))})},Mb=(a,b,c,d)=>{c=V(c);d=V(d);U([],[a,b],e=>{Pg(e[0].s.ba,c,d);return[]})};Mb.g="vpppp";
var Nb=(a,b,c)=>{function d(f){var g=(w(),H)[f>>2];f=(w(),H)[f+4>>2];return new e((w(),y).buffer,f,g)}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=V(c);T(a,{name:c,v:d,K:d},{Tb:!0})};Nb.g="vpip";var Qg=Object.assign({optional:!0},Lg),Ob=a=>{T(a,Qg)};Ob.g="vpp";
var Pb=(a,b)=>{b=V(b);T(a,{name:b,v(c){var d=(w(),H)[c>>2];d=Q(c+4,d,!0);M(c);return d},F(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new W("Cannot pass non-string to std::string");var f=e?Te(d):d.length;var g=$c(4+f+1),k=g+4;(w(),H)[g>>2]=f;e?Ve(d,k,f+1):(w(),A).set(d,k);null!==c&&c.push(M,g);return g},K:Of,H(c){M(c)}})};Pb.g="vpp";
var Rg=new TextDecoder("utf-16le"),Sg=(a,b,c)=>{a>>=1;b=pe((w(),F),a,b/2,c);return Rg.decode((w(),F).slice(a,b))},Tg=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e){var f=a.charCodeAt(e);(w(),z)[b>>1]=f;b+=2}(w(),z)[b>>1]=0;return b-d},Ug=a=>2*a.length,Vg=(a,b,c)=>{var d="";a>>=2;for(var e=0;!(e>=b/4);e++){var f=(w(),H)[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Wg=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=
0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;(w(),G)[b>>2]=f;b+=4;if(b+4>c)break}(w(),G)[b>>2]=0;return b-d},Xg=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Qb=(a,b,c)=>{c=V(c);if(2===b){var d=Sg;var e=Tg;var f=Ug}else d=Vg,e=Wg,f=Xg;T(a,{name:c,v:g=>{var k=(w(),H)[g>>2];k=d(g+4,k*b,!0);M(g);return k},F:(g,k)=>{if("string"!=typeof k)throw new W(`Cannot pass non-string to C++ string type ${c}`);var l=f(k),m=$c(4+l+b);(w(),H)[m>>2]=l/b;e(k,m+4,l+b);null!==g&&
g.push(M,m);return m},K:Of,H(g){M(g)}})};Qb.g="vppp";var Rb=(a,b,c,d,e,f)=>{Mf[a]={name:V(b),Ra:X(c,d),Y:X(e,f),bb:[]}};Rb.g="vpppppp";var Sb=(a,b,c,d,e,f,g,k,l,m)=>{Mf[a].bb.push({Jb:V(b),Pb:c,ma:X(d,e),Ob:f,nc:g,mc:X(k,l),oc:m})};Sb.g="vpppppppppp";var Tb=(a,b)=>{b=V(b);T(a,{gb:!0,name:b,v:()=>{},F:()=>{}})};Tb.g="vpp";
var Ub=(a,b,c,d)=>{function e(k){var l=Q(a+36);Kf(`'Could not load dynamic lib: ${l}\n${k}`);--O;ae(()=>N.get(c)(a,d))}function f(){--O;ae(()=>N.get(b)(a,d))}O+=1;var g=Lf(a,{I:!0});g?g.then(f,e):e()};Ub.g="vpppp";function Yg(a){var b=Zg,c=b.P.pop()||b.fa.length;b.fa[c]=a;return c}function $g(a){var b=Zg;b.fa[a]=void 0;b.P.push(a)}class ah{fa=[void 0];P=[];get(a){return this.fa[a]}has(a){return void 0!==this.fa[a]}}
var Zg=new ah,bh=()=>{var a={};a.promise=new Promise((b,c)=>{a.reject=c;a.resolve=b});a.id=Yg(a);return a},ch=async()=>{const a=be,b=[];var c=bh();b.push(c.promise);gd(c.id);for(const d of Object.keys(Hd)){const e=Number(d);e===a||Id.has(e)||(c=bh(),jd(e,c.id),Jd[e]=c,b.push(c.promise))}await Promise.all(b);Jd={}};function Vb(){if(p)return P(17,2);if(be)return ch();for(const a of Object.keys(Hd)){const b=Number(a);Id.has(b)||kd(b)}}Vb.g="v";
function Wb(){var a=$c(4*(ka.length+1)),b=a;ka.forEach(c=>{var d=(w(),H),e=b>>2,f=Te(c)+1,g=$c(f);g&&Ve(c,g,f);d[e]=g;b+=4});(w(),H)[b>>2]=0;return a}Wb.g="p";var Xb=a=>{Ba(a,!ba,1,!aa,262144,!1);Ca()};Xb.g="vp";var Da=a=>{Wd||(Atomics.waitAsync((w(),G),a>>2,a).value.then(Ga),a+=120,Atomics.store((w(),G),a>>2,1))};Da.g="vp";var Ga=()=>{var a=Zc();a&&ae(()=>{Da(a);rd()})},Yb=(a,b)=>{a==b?setTimeout(Ga):p?postMessage({Da:a,V:"checkMailbox"}):(a=Hd[a])&&a.postMessage({V:"checkMailbox"})};Yb.g="vpp";
var dh=[],Zb=(a,b,c,d,e,f,g)=>{dh.length=0;var k=e>>3;for(d=e+d>>3;k<d;){var l;(w(),I)[k++]?l=(w(),I)[k++]:l=(w(),La)[k++];dh.push(l)}a=b?He[b]:eh[a];be=c;c=a(...dh);be=0;if(f)c.then(m=>nd(f,g,m));else return c};Zb.g="dippippp";var $b=()=>{ce=!1;O=0};$b.g="v";var ac=a=>{p?postMessage({V:"cleanupThread",Ua:a}):Md(a)};ac.g="vp";var bc=a=>{p?postMessage({V:"markAsFinished",Ua:a}):Od(a)};bc.g="vp";var cc=()=>{};cc.g="vp";var dc=(a,b)=>{a=Y(a);b=Y(b);a.set(b)};dc.g="vpp";
var fh=[],gh=a=>{var b=fh.length;fh.push(a);return b},hh=(a,b)=>{for(var c=Array(a),d=0;d<a;++d)c[d]=Ng((w(),H)[b+4*d>>2],`parameter ${d}`);return c},ih=(a,b,c)=>{var d=[];a=a(d,c);d.length&&((w(),H)[b>>2]=pg(d));return a},jh={},kh=a=>{var b=jh[a];return void 0===b?V(a):b},ec=(a,b,c)=>{var [d,...e]=hh(a,b);b=d.F.bind(d);var f=e.map(l=>l.K.bind(l));a--;var g={toValue:Y};a=f.map((l,m)=>{var n=`argFromPtr${m}`;g[n]=l;return`${n}(args${m?"+"+8*m:""})`});switch(c){case 0:var k="toValue(handle)";break;
case 2:k="new (toValue(handle))";break;case 3:k="";break;case 1:g.getStringOrSymbol=kh,k="toValue(handle)[getStringOrSymbol(methodName)]"}k+=`(${a})`;d.gb||(g.toReturnWire=b,g.emval_returnValue=ih,k=`return emval_returnValue(toReturnWire, destructorsRef, ${k})`);k=`return function (handle, methodName, destructorsRef, args) {\n${k}\n}`;c=(new Function(Object.keys(g),k))(...Object.values(g));k=`methodCaller<(${e.map(l=>l.name)}) => ${d.name}>`;return gh(Fe(k,c))};ec.g="pipi";
var gc=a=>{if(!a)return pg(globalThis);a=kh(a);return pg(globalThis[a])};gc.g="pp";var hc=a=>{a=kh(a);return pg(h[a])};hc.g="pp";var ic=(a,b)=>{a=Y(a);b=Y(b);return pg(a[b])};ic.g="ppp";var jc=a=>{9<a&&(Jg[a+1]+=1)};jc.g="vp";var kc=(a,b)=>{a=Y(a);b=Y(b);return a instanceof b};kc.g="ipp";var lc=(a,b,c,d,e)=>fh[a](b,c,d,e);lc.g="dppppp";var mc=a=>{a=Y(a);return"number"==typeof a};mc.g="ip";var nc=a=>{a=Y(a);return"string"==typeof a};nc.g="ip";var oc=a=>pg(kh(a));oc.g="pp";
var pc=a=>{var b=Y(a);Nf(b);fc(a)};pc.g="vp";var qc=(a,b,c)=>{a=Y(a);b=Y(b);c=Y(c);a[b]=c};qc.g="vppp";var rc=a=>{a=Y(a);return pg(typeof a)};rc.g="pp";
function sc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(w(),G)[b>>2]=a.getUTCSeconds();(w(),G)[b+4>>2]=a.getUTCMinutes();(w(),G)[b+8>>2]=a.getUTCHours();(w(),G)[b+12>>2]=a.getUTCDate();(w(),G)[b+16>>2]=a.getUTCMonth();(w(),G)[b+20>>2]=a.getUTCFullYear()-1900;(w(),G)[b+24>>2]=a.getUTCDay();a=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;(w(),G)[b+28>>2]=a}sc.g="vjp";
var lh=a=>0===a%4&&(0!==a%100||0===a%400),mh=[0,31,60,91,121,152,182,213,244,274,305,335],nh=[0,31,59,90,120,151,181,212,243,273,304,334];
function tc(a,b){a=-9007199254740992>a||9007199254740992<a?NaN:Number(a);a=new Date(1E3*a);(w(),G)[b>>2]=a.getSeconds();(w(),G)[b+4>>2]=a.getMinutes();(w(),G)[b+8>>2]=a.getHours();(w(),G)[b+12>>2]=a.getDate();(w(),G)[b+16>>2]=a.getMonth();(w(),G)[b+20>>2]=a.getFullYear()-1900;(w(),G)[b+24>>2]=a.getDay();var c=(lh(a.getFullYear())?mh:nh)[a.getMonth()]+a.getDate()-1|0;(w(),G)[b+28>>2]=c;(w(),G)[b+36>>2]=-(60*a.getTimezoneOffset());c=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();var d=(new Date(a.getFullYear(),
0,1)).getTimezoneOffset();a=(c!=d&&a.getTimezoneOffset()==Math.min(d,c))|0;(w(),G)[b+32>>2]=a}tc.g="vjp";
function uc(a){var b=new Date((w(),G)[a+20>>2]+1900,(w(),G)[a+16>>2],(w(),G)[a+12>>2],(w(),G)[a+8>>2],(w(),G)[a+4>>2],(w(),G)[a>>2],0);if(isNaN(b.getTime()))a=-1;else{var c=(w(),G)[a+32>>2],d=b.getTimezoneOffset(),e=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),f=(new Date(b.getFullYear(),0,1)).getTimezoneOffset(),g=Math.min(f,e);0>c?(w(),G)[a+32>>2]=Number(e!=f&&g==d):0<c!=(g==d)&&(e=Math.max(f,e),b.setTime(b.getTime()+6E4*((0<c?g:e)-d)));(w(),G)[a+24>>2]=b.getDay();c=(lh(b.getFullYear())?
mh:nh)[b.getMonth()]+b.getDate()-1|0;(w(),G)[a+28>>2]=c;(w(),G)[a>>2]=b.getSeconds();(w(),G)[a+4>>2]=b.getMinutes();(w(),G)[a+8>>2]=b.getHours();(w(),G)[a+12>>2]=b.getDate();(w(),G)[a+16>>2]=b.getMonth();(w(),G)[a+20>>2]=b.getYear();a=b.getTime()/1E3}return BigInt(a)}uc.g="jp";
function vc(a,b,c,d,e,f,g){if(p)return P(18,1,a,b,c,d,e,f,g);e=-9007199254740992>e||9007199254740992<e?NaN:Number(e);try{var k=S(d),l=FS.ja(k,a,e,b,c),m=l.A;(w(),G)[f>>2]=l.fa;(w(),H)[g>>2]=m;return 0}catch(n){if("undefined"==typeof FS||"ErrnoError"!==n.name)throw n;return-n.B}}vc.g="ipiiijpp";
function wc(a,b,c,d,e,f){if(p)return P(19,1,a,b,c,d,e,f);f=-9007199254740992>f||9007199254740992<f?NaN:Number(f);try{var g=S(e);if(c&2){c=f;if(!FS.isFile(g.node.mode))throw new FS.h(43);if(!(d&2)){var k=(w(),A).slice(a,a+b);FS.la(g,k,c,b,d)}}}catch(l){if("undefined"==typeof FS||"ErrnoError"!==l.name)throw l;return-l.B}}wc.g="ippiiij";
var xc=(a,b,c,d)=>{var e=(new Date).getFullYear(),f=(new Date(e,0,1)).getTimezoneOffset();e=(new Date(e,6,1)).getTimezoneOffset();var g=Math.max(f,e);(w(),H)[a>>2]=60*g;(w(),G)[b>>2]=Number(f!=e);b=k=>{var l=Math.abs(k);return`UTC${0<=k?"-":"+"}${String(Math.floor(l/60)).padStart(2,"0")}${String(l%60).padStart(2,"0")}`};a=b(f);b=b(e);e<f?(Ve(a,c,17),Ve(b,d,17)):(Ve(a,d,17),Ve(b,c,17))};xc.g="vpppp";var Ec=()=>performance.timeOrigin+performance.now();Ec.g="d";var Ac=()=>Date.now();Ac.g="d";
var oh=1;function yc(a,b,c){if(!(0<=a&&3>=a))return 28;if(0===a)a=Date.now();else if(oh)a=performance.timeOrigin+performance.now();else return 52;a=Math.round(1E6*a);(w(),I)[c>>3]=BigInt(a);return 0}yc.g="iijp";var zc=()=>{};zc.g="v";var Bc=a=>t(Q(a));Bc.g="vp";var Cc=()=>{O+=1;throw"unwind";};Cc.g="v";var Dc=()=>2147483648;Dc.g="p";var Fc=()=>navigator.hardwareConcurrency;Fc.g="i";var Gc=a=>{$g(a)};Gc.g="vp";
var Hc=(a,b,c)=>{a=Zg.get(a);switch(b){case 0:a.resolve(c);break;case 1:a.resolve(Zg.get(c).promise);break;case 2:a.resolve(Zg.get(c).promise);$g(c);break;case 3:a.reject(c)}};Hc.g="vpip";var Ic=a=>{var b=(w(),A).length;a>>>=0;if(a<=b||2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-qa.buffer.byteLength+65535)/65536|0;try{qa.grow(d);ra();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1};
Ic.g="ip";var ph={},rh=()=>{if(!qh){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:(globalThis.navigator?.language??"C").replace("-","_")+".UTF-8",_:da||"./this.program"},b;for(b in ph)void 0===ph[b]?delete a[b]:a[b]=ph[b];var c=[];for(b in a)c.push(`${b}=${a[b]}`);qh=c}return qh},qh;function Jc(a,b){if(p)return P(20,1,a,b);var c=0,d=0,e;for(e of rh()){var f=b+c;(w(),H)[a+d>>2]=f;c+=Ve(e,f,Infinity)+1;d+=4}return 0}Jc.g="ipp";
function Kc(a,b){if(p)return P(21,1,a,b);var c=rh();(w(),H)[a>>2]=c.length;a=0;for(var d of c)a+=Te(d)+1;(w(),H)[b>>2]=a;return 0}Kc.g="ipp";function Mc(a){if(p)return P(22,1,a);try{var b=S(a);FS.close(b);return 0}catch(c){if("undefined"==typeof FS||"ErrnoError"!==c.name)throw c;return c.B}}Mc.g="ii";
function Nc(a,b){if(p)return P(23,1,a,b);try{var c=S(a),d=c.C?2:FS.isDir(c.mode)?3:FS.isLink(c.mode)?7:4;(w(),y)[b]=d;(w(),z)[b+2>>1]=0;(w(),I)[b+8>>3]=BigInt(0);(w(),I)[b+16>>3]=BigInt(0);return 0}catch(e){if("undefined"==typeof FS||"ErrnoError"!==e.name)throw e;return e.B}}Nc.g="iip";
function Oc(a,b,c,d){if(p)return P(24,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(w(),H)[a>>2],l=(w(),H)[a+4>>2];a+=8;var m=FS.read(e,(w(),y),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(w(),H)[d>>2]=n;return 0}catch(r){if("undefined"==typeof FS||"ErrnoError"!==r.name)throw r;return r.B}}Oc.g="iippp";
function Pc(a,b,c,d){if(p)return P(25,1,a,b,c,d);b=-9007199254740992>b||9007199254740992<b?NaN:Number(b);try{if(isNaN(b))return 22;var e=S(a);FS.llseek(e,b,c);(w(),I)[d>>3]=BigInt(e.position);e.Ga&&0===b&&0===c&&(e.Ga=null);return 0}catch(f){if("undefined"==typeof FS||"ErrnoError"!==f.name)throw f;return f.B}}Pc.g="iijip";
function Qc(a,b,c,d){if(p)return P(26,1,a,b,c,d);try{a:{var e=S(a);a=b;for(var f,g=b=0;g<c;g++){var k=(w(),H)[a>>2],l=(w(),H)[a+4>>2];a+=8;var m=FS.write(e,(w(),y),k,l,f);if(0>m){var n=-1;break a}b+=m;if(m<l)break;"undefined"!=typeof f&&(f+=m)}n=b}(w(),H)[d>>2]=n;return 0}catch(r){if("undefined"==typeof FS||"ErrnoError"!==r.name)throw r;return r.B}}Qc.g="iippp";function Sc(...a){return L.heif_error_success(...a)}Sc.Ba=!0;var Uc=(a,b)=>Ye((w(),A).subarray(a,a+b));Uc.g="ipp";p||Yd();
(()=>{var a={mb:Promise.resolve(),canHandle:b=>!h.noWasmDecoding&&b.endsWith(".so"),handle:async(b,c)=>a.mb=a.mb.then(async()=>{try{var d=await Le(b,{I:!0,pa:!0},c,{})}catch(e){throw Error(`failed to instantiate wasm: ${c}: ${e}`);}ge[c]=d;return b})};fe.push(a)})();FS.createPreloadedFile=(a,b,c,d,e,f,g,k,l,m)=>{of(a,b,c,d,e,k,l,m).then(f).catch(g)};FS.Oc=of;FS.da=Array(4096);FS.mount(R,{},"/");FS.mkdir("/tmp");FS.mkdir("/home");FS.mkdir("/home/web_user");
(function(){FS.mkdir("/dev");FS.registerDevice(FS.makedev(1,3),{read:()=>0,write:(d,e,f,g)=>g,llseek:()=>0});FS.mkdev("/dev/null",FS.makedev(1,3));df(FS.makedev(5,0),ff);df(FS.makedev(6,0),gf);FS.mkdev("/dev/tty",FS.makedev(5,0));FS.mkdev("/dev/tty1",FS.makedev(6,0));var a=new Uint8Array(1024),b=0,c=()=>{0===b&&(Ye(a),b=a.byteLength);return a[--b]};FS.createDevice("/dev","random",c);FS.createDevice("/dev","urandom",c);FS.mkdir("/dev/shm");FS.mkdir("/dev/shm/tmp")})();
(function(){FS.mkdir("/proc");var a=FS.mkdir("/proc/self");FS.mkdir("/proc/self/fd");FS.mount({mount(){var b=FS.createNode(a,"fd",16895,73);b.o={llseek:R.o.llseek};b.m={ia(c,d){c=+d;var e=S(c);c={parent:null,mount:{jb:"fake"},m:{readlink:()=>e.path},id:c+1};return c.parent=c},sa(){return Array.from(FS.streams.entries()).filter(([,c])=>c).map(([c])=>c.toString())}};return b}},{},"/proc/self/fd")})();FS.Kb={MEMFS:R};
(()=>{let a=fg.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof fg&&c instanceof fg))return!1;var d=this.l.D.s,e=this.l.A;c.l=c.l;var f=c.l.D.s;for(c=c.l.A;d.M;)e=d.ua(e),d=d.M;for(;f.M;)c=f.ua(c),f=f.M;return d===f&&e===c},clone:function(){this.l.A||Yf(this);if(this.l.qa)return this.l.count.value+=1,this;var c=bg,d=Object,e=d.create,f=Object.getPrototypeOf(this),g=this.l;c=c(e.call(d,f,{l:{value:{count:g.count,ha:g.ha,qa:g.qa,A:g.A,D:g.D,J:g.J,R:g.R}}}));c.l.count.value+=1;c.l.ha=
!1;return c},["delete"](){this.l.A||Yf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");ag(this);var c=this.l;--c.count.value;0===c.count.value&&(c.J?c.R.Y(c.J):c.D.s.Y(c.A));this.l.qa||(this.l.J=void 0,this.l.A=void 0)},isDeleted:function(){return!this.l.A},deleteLater:function(){this.l.A||Yf(this);if(this.l.ha&&!this.l.qa)throw new W("Object already scheduled for deletion");cg.push(this);1===cg.length&&eg&&eg(dg);this.l.ha=!0;return this}});const b=Symbol.dispose;
b&&(a[b]=a["delete"])})();
Object.assign(vg.prototype,{Nb(a){this.nb&&(a=this.nb(a));return a},Ya(a){this.Y?.(a)},K:Of,v:function(a){function b(){return this.za?ug(this.s.ba,{D:this.jc,A:c,R:this,J:a}):ug(this.s.ba,{D:this,A:a})}var c=this.Nb(a);if(!c)return this.Ya(a),null;var d=tg(this.s,c);if(void 0!==d){if(0===d.l.count.value)return d.l.A=c,d.l.J=a,d.clone();d=d.clone();this.Ya(a);return d}d=this.s.Lb(c);d=gg[d];if(!d)return b.call(this);d=this.ya?d.Db:d.pointerType;var e=rg(c,this.s,d.s);return null===e?b.call(this):this.za?
ug(d.s.ba,{D:d,A:e,R:this,J:a}):ug(d.s.ba,{D:d,A:e})}});Nd.push(()=>{ph.VIPS_DISC_THRESHOLD=2147483648;ph.VIPS_MAX_THREADS=6<navigator.hardwareConcurrency?navigator.hardwareConcurrency:6;ph.VIPS_CONCURRENCY=1});
Ra.push(()=>{const a=Object.getOwnPropertyDescriptor(h.SourceCustom.prototype,"onRead");Object.defineProperty(h.SourceCustom.prototype,"onRead",{set(c){return a.set.call(this,d=>pg(c(d)))}});const b=Object.getOwnPropertyDescriptor(h.TargetCustom.prototype,"onWrite");Object.defineProperty(h.TargetCustom.prototype,"onWrite",{set(c){return b.set.call(this,d=>c(Y(d)))}})});Object.assign(fg.prototype,{preventAutoDelete:function(){const a=cg.indexOf(this);-1<a&&cg.splice(a,1);this.l.ha=!1;return this}});
p||(h.wasmMemory?qa=h.wasmMemory:qa=new WebAssembly.Memory({initial:(h.INITIAL_MEMORY||1073741824)/65536,maximum:32768,shared:!0}),ra());h.preloadPlugins&&(fe=h.preloadPlugins);h.noExitRuntime&&(ce=h.noExitRuntime);h.print&&(ja=h.print);h.printErr&&(t=h.printErr);h.dynamicLibraries&&(ka=h.dynamicLibraries);h.wasmBinary&&(la=h.wasmBinary);h.arguments&&(ca=h.arguments);h.thisProgram&&(da=h.thisProgram);if(h.preInit)for("function"==typeof h.preInit&&(h.preInit=[h.preInit]);0<h.preInit.length;)h.preInit.shift()();
h.ENV=ph;h.addRunDependency=Sd;h.removeRunDependency=Rd;h.addFunction=Ce;h.FS_preloadFile=of;h.FS_unlink=(...a)=>FS.unlink(...a);h.FS_createPath=(...a)=>FS.createPath(...a);h.FS_createDevice=(...a)=>FS.createDevice(...a);h.FS=FS;h.FS_createDataFile=(...a)=>FS.createDataFile(...a);h.FS_createLazyFile=(...a)=>FS.createLazyFile(...a);h.setAutoDeleteLater=a=>{Zf=a};h.deletionQueue=cg;h.setDelayFunction=a=>{eg=a;cg.length&&eg&&eg(dg)};
var eh=[Tc,de,Ef,cb,db,eb,fb,gb,hb,ib,jb,kb,lb,mb,nb,ob,pb,Vb,vc,wc,Jc,Kc,Mc,Nc,Oc,Pc,Qc],He={};function sh(a){for(var b=(w(),F)[a+6>>1];13===b&&!(16<(w(),H)[a>>2]);){var c=(w(),H)[a+8>>2],d=(w(),H)[c>>2];if(0===d){b=0;break}else if(0===(w(),H)[(c>>2)+1])a=d,b=(w(),F)[d+6>>1];else break}return[a,b]}
function Rc(a,b,c,d){w();var e=(w(),H)[(a>>2)+1],f=(w(),H)[(a>>2)+6],g=(w(),H)[(a>>2)+2],k=(w(),H)[(a>>2)+5];a=sh((w(),H)[(a>>2)+3])[1];var l=wd(),m=l,n=[],r=!1;if(15===a)throw Error("complex ret marshalling nyi");if(0>a||15<a)throw Error("Unexpected rtype "+a);if(4===a||13===a)n.push(c),r=!0;for(var u=0;u<f;u++){var q=(w(),H)[(d>>2)+u],v=sh((w(),H)[(g>>2)+u]),x=v[0];v=v[1];switch(v){case 1:case 10:case 9:n.push((w(),H)[q>>2]);break;case 2:n.push((w(),Ka)[q>>2]);break;case 3:n.push((w(),La)[q>>3]);
break;case 5:n.push((w(),A)[q]);break;case 6:n.push((w(),y)[q]);break;case 7:n.push((w(),F)[q>>1]);break;case 8:n.push((w(),z)[q>>1]);break;case 11:case 12:n.push((w(),Ma)[q>>3]);break;case 4:n.push((w(),Ma)[q>>3]);n.push((w(),Ma)[(q>>3)+1]);break;case 13:v=(w(),H)[x>>2];x=(w(),F)[x+4>>1];m-=v;m&=~(x-1);(w(),y).subarray(m,m+v).set((w(),y).subarray(q,q+v));n.push(m);break;case 14:n.push((w(),H)[q>>2]);break;case 15:throw Error("complex marshalling nyi");default:throw Error("Unexpected type "+v);}}if(k&
1){k=[];for(u=e-1;u>=f;u--)switch(q=(w(),H)[(d>>2)+u],v=sh((w(),H)[(g>>2)+u]),x=v[0],v=v[1],v){case 5:case 6:--m;m&=-1;(w(),A)[m]=(w(),A)[q];break;case 7:case 8:m-=2;m&=-2;(w(),F)[m>>1]=(w(),F)[q>>1];break;case 1:case 9:case 10:case 2:m-=4;m&=-4;(w(),H)[m>>2]=(w(),H)[q>>2];break;case 3:case 11:case 12:m-=8;m&=-8;(w(),H)[m>>2]=(w(),H)[q>>2];(w(),H)[(m>>2)+1]=(w(),H)[(q>>2)+1];break;case 4:m-=16;m&=-8;(w(),H)[m>>2]=(w(),H)[q>>2];(w(),H)[(m>>2)+1]=(w(),H)[(q>>2)+1];(w(),H)[(m>>2)+2]=(w(),H)[(q>>2)+2];
(w(),H)[(m>>2)+3]=(w(),H)[(q>>2)+3];break;case 13:m-=4;m&=-4;k.push([m,q,(w(),H)[x>>2],(w(),F)[x+4>>1]]);break;case 14:m-=4;m&=-4;(w(),H)[m>>2]=(w(),H)[q>>2];break;case 15:throw Error("complex arg marshalling nyi");default:throw Error("Unexpected argtype "+v);}n.push(m);for(u=0;u<k.length;u++)e=k[u],d=e[0],q=e[1],v=e[2],x=e[3],m-=v,m&=~(x-1),(w(),y).subarray(m,m+v).set((w(),y).subarray(q,q+v)),(w(),H)[d>>2]=m}ud(m);vd(0);b=N.get(b).apply(null,n);ud(l);if(!r)switch(a){case 0:break;case 1:case 9:case 10:(w(),
H)[c>>2]=b;break;case 2:(w(),Ka)[c>>2]=b;break;case 3:(w(),La)[c>>3]=b;break;case 5:case 6:(w(),A)[c+0]=b;break;case 7:case 8:(w(),F)[c>>1]=b;break;case 11:case 12:(w(),Ma)[c>>3]=b;break;case 14:(w(),H)[c>>2]=b;break;case 15:throw Error("complex ret marshalling nyi");default:throw Error("Unexpected rtype "+a);}}Rc.g="viiii";var Zc,$c,M,ad,bd,cd,Ea,dd,ed,fd,gd,hd,jd,kd,ld,Ba,md,Ha,nd,od,pd,qd,rd,sd,Sa,td,ud,vd,wd,xd,yd,zd,Ad,N,L;
function th(a=[]){var b=Ge("main").Ta;if(b){a.unshift(da);var c=a.length,d=vd(4*(c+1)),e=d,f;for(f of a)(w(),H)[e>>2]=We(f),e+=4;(w(),H)[e>>2]=0;try{var g=b(c,d);Lc(g,!0)}catch(k){Fd(k)}}}
function za(a=ca){function b(){h.calledRun=!0;if(!oa&&(Oa(),sa?.(h),h.onRuntimeInitialized?.(),h.noInitialRun||th(a),!p)){if(h.postRun)for("function"==typeof h.postRun&&(h.postRun=[h.postRun]);h.postRun.length;){var c=h.postRun.shift();ne.push(c)}Pa(ne)}}if(0<Pd)Qd=za;else if(p)sa?.(h),Oa();else{if(h.preRun)for("function"==typeof h.preRun&&(h.preRun=[h.preRun]);h.preRun.length;)Nd.push(h.preRun.shift());Pa(Nd);0<Pd?Qd=za:h.setStatus?(h.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>h.setStatus(""),
1);b()},1)):b()}}var Qa;p||(Qa=await (ya()),za());Ia?moduleRtn=h:moduleRtn=new Promise((a,b)=>{sa=a;ta=b});
;return moduleRtn}})();if(typeof exports==="object"&&typeof module==="object"){module.exports=Vips;module.exports.default=Vips}else if(typeof define==="function"&&define["amd"])define([],()=>Vips);var isPthread=globalThis.name=="em-pthread";isPthread&&Vips();
